Repository gradio-app/gradio, pull requests merged in 2023-08, with the labels that each got.

#5061 Ensure `gradio_client` is backwards compatible with `gradio==3.24.1`
  .changeset/tired-regions-punch.md
  client/python/gradio_client/serializing.py
  requirements.txt
Labels: v: patch, t: fix

#5076 Add deploy_discord to docs
  .changeset/lovely-taxes-try.md
  client/python/gradio_client/client.py
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/blocks-and-event-listeners.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
Labels: docs/website

#5129 [Spaces] ZeroGPU Queue fix
  .changeset/true-camels-shave.md
  gradio/blocks.py
  gradio/utils.py
  test/test_blocks.py
Labels: t: fix

#5114 Reset textbox value to empty string when value is None
  .changeset/good-years-ask.md
  js/textbox/shared/Textbox.svelte
Labels: no-visual-update

#5057 Return final output for generators in Client.predict
  .changeset/two-spies-shine.md
  .config/.prettierrc.json
  .github/workflows/backend.yml
  client/js/src/client.ts
  client/python/gradio_client/client.py
  client/python/test/conftest.py
  client/python/test/test_client.py
  scripts/install_test_requirements.sh
Labels: t: highlight

#5135 Fix dataset features and dataset preview for HuggingFaceDatasetSaver
  .changeset/new-icons-refuse.md
  gradio/flagging.py
  test/test_flagging.py
Labels: t: fix

#5188 Fix the images in the theme builder to use permanent URI
  .changeset/light-mice-bake.md
  gradio/themes/app.py
  gradio/themes/builder_app.py
Labels: v: patch

#5173 Ensure gradio client works as expected for functions that return nothing.
  .changeset/legal-donuts-burn.md
  client/js/src/client.ts
Labels: v: patch

#5253 Ensure File component uploads files to the server.
  .changeset/curly-hands-carry.md
  .config/.prettierignore
  guides/08_other-tutorials/creating-a-new-component.md
  guides/cn/07_other-tutorials/creating-a-new-component.md
  js/app/src/Login.svelte
  js/audio/index.svelte
  js/audio/interactive/InteractiveAudio.svelte
  js/audio/static/StaticAudio.svelte
  js/chatbot/Chatbot.stories.svelte
  js/chatbot/static/ChatBot.svelte
  js/chatbot/utils.ts
  js/checkbox/index.svelte
  js/checkboxgroup/index.svelte
  js/code/index.svelte
  js/colorpicker/index.svelte
  js/dataframe/index.svelte
  js/dropdown/index.svelte
  js/file/index.svelte
  js/file/interactive/InteractiveFile.svelte
  js/file/static/StaticFile.svelte
  js/image/index.svelte
  js/model3D/index.svelte
  js/number/index.svelte
  js/radio/index.svelte
  js/slider/index.svelte
  js/textbox/index.svelte
  js/timeseries/index.svelte
  js/timeseries/static/StaticTimeseries.svelte
  js/video/index.svelte
  js/video/interactive/InteractiveVideo.svelte
  js/video/static/StaticVideo.svelte
  pnpm-lock.yaml
Labels: t: fix

#5265 Removes scrollbar from File preview when not needed
  .changeset/pink-rockets-start.md
  js/file/shared/FilePreview.svelte
  pnpm-lock.yaml
Labels: v: patch

#5276 Ensure `Blocks` translation copy renders correctly
  .changeset/young-plums-swim.md
  js/app/src/Blocks.svelte
Labels: v: patch, t: fix

#5248 Enable streaming audio in python client
  .changeset/chilly-fans-make.md
  .github/workflows/backend.yml
  client/python/gradio_client/data_classes.py
  client/python/gradio_client/serializing.py
  client/python/gradio_client/utils.py
  client/python/test/conftest.py
  client/python/test/requirements.txt
  client/python/test/test_client.py
  gradio/blocks.py
  gradio/components/audio.py
Labels: t: highlight

#5258 Chatbot Avatar Images
  .changeset/red-trains-wonder.md
  demo/chatbot_multimodal/avatar.png
  demo/chatbot_multimodal/run.ipynb
  demo/chatbot_multimodal/run.py
  gradio/components/chatbot.py
  js/chatbot/static/ChatBot.svelte
  js/chatbot/static/StaticChatbot.svelte
  test/test_components.py
Labels: t: feat

#5295 Allow caching examples with streamed output
  .changeset/full-melons-pick.md
  client/python/gradio_client/serializing.py
  demo/stream_audio_out/audio/cantina.wav
  demo/stream_audio_out/run.ipynb
  demo/stream_audio_out/run.py
  gradio/helpers.py
  test/test_helpers.py
Labels: t: fix

#5312 only start listening for events after the components are mounted
  .changeset/large-bats-say.md
  js/app/src/Blocks.svelte
Labels: v: patch, t: fix

#5313 Restores missing part of bottom border on file component
  .changeset/warm-nails-brush.md
  js/file/static/StaticFile.svelte
Labels: t: fix

#5324 ensure login form has correct styles
  .changeset/itchy-needles-float.md
  .devcontainer/devcontainer.json
  demo/markdown_example/run.ipynb
  demo/markdown_example/run.py
  js/_website/src/lib/components/EventListeners.svelte
  js/_website/src/lib/components/FunctionDoc.svelte
  js/_website/src/routes/[[version]]/docs/[doc=valid_doc]/+page.server.ts
  js/_website/src/routes/[[version]]/docs/[doc=valid_doc]/+page.svelte
  js/app/src/Login.svelte
  js/markdown/static/prism.css
  js/storybook/preview.ts
  js/textbox/interactive/InteractiveTextbox.svelte
Labels: v: patch, t: fix

#5284 Minor bug fix sweep
  .changeset/fancy-bats-deny.md
  demo/barplot_component/run.ipynb
  demo/barplot_component/run.py
  demo/blocks_essay/run.ipynb
  demo/blocks_essay/run.py
  demo/blocks_flashcards/run.ipynb
  demo/blocks_flashcards/run.py
  demo/blocks_joined/run.ipynb
  demo/blocks_joined/run.py
  demo/blocks_kitchen_sink/run.ipynb
  demo/blocks_kitchen_sink/run.py
  demo/blocks_layout/run.ipynb
  demo/blocks_layout/run.py
  demo/blocks_style/run.ipynb
  demo/blocks_style/run.py
  demo/chatbot_multimodal/run.ipynb
  demo/chatbot_multimodal/run.py
  demo/dashboard/run.ipynb
  demo/dashboard/run.py
  demo/diff_texts/run.ipynb
  demo/diff_texts/run.py
  demo/fake_gan/run.ipynb
  demo/fake_gan/run.py
  demo/fake_gan_no_input/run.ipynb
  demo/fake_gan_no_input/run.py
  demo/gallery_component/run.ipynb
  demo/gallery_component/run.py
  demo/image_segmentation/run.ipynb
  demo/image_segmentation/run.py
  demo/kitchen_sink/run.ipynb
  demo/kitchen_sink/run.py
  demo/lineplot_component/run.ipynb
  demo/lineplot_component/run.py
  demo/map_airbnb/run.ipynb
  demo/map_airbnb/run.py
  demo/native_plots/bar_plot_demo.py
  demo/native_plots/line_plot_demo.py
  demo/native_plots/scatter_plot_demo.py
  demo/rows_and_columns/run.ipynb
  demo/rows_and_columns/run.py
  demo/scatterplot_component/run.ipynb
  demo/scatterplot_component/run.py
  demo/stable-diffusion/run.ipynb
  demo/stable-diffusion/run.py
  gradio/blocks.py
  gradio/components/checkboxgroup.py
  gradio/components/gallery.py
  gradio/layouts.py
  js/_website/generate_jsons/src/docs/__init__.py
  js/_website/src/routes/[[version]]/docs/block-layouts/+page.server.ts
  js/highlightedtext/static/Highlightedtext.svelte
  pnpm-lock.yaml
Labels: v: patch
