Repository gradio-app/gradio, pull requests merged in 2023-11, with the labels that each got.

#6211 fix`FileExplorer` preprocess
  .changeset/tame-singers-join.md
  gradio/components/file_explorer.py
Labels: v: patch, t: fix

#6227 Add that api routes are automatically named to CHANGELOG.
  .changeset/five-women-brake.md
  CHANGELOG.md
  gradio/layouts/column.py
Labels: v: patch

#6244 Fix stories
  js/audio/Audio.stories.svelte
  js/file/File.stories.svelte
  js/gallery/Gallery.stories.svelte
  js/image/Image.stories.svelte
  js/radio/Radio.stories.svelte
  js/video/Video.stories.svelte
  pnpm-lock.yaml
Labels: v: patch

#6243 Some tweaks to the Custom Components Guide
  .changeset/hot-donuts-notice.md
  guides/05_custom-components/01_five-minute-guide.md
  guides/05_custom-components/02_key-component-concepts.md
  guides/05_custom-components/03_configuration.md
  guides/05_custom-components/06_frequently-asked-questions.md
  guides/09_other-tutorials/creating-a-new-component.md
  js/_website/src/routes/redirects.js
Labels: v: patch

#6292 chore: update versions
  .changeset/cuddly-snakes-dress.md
  .changeset/quiet-walls-float.md
  .changeset/twelve-dolls-lay.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
Labels: no-visual-update

#6326 Fix Model3D template
  .changeset/vast-gifts-win.md
  gradio/cli/commands/components/_create_utils.py
  test/test_gradio_component_cli.py
Labels: v: patch

#6333 Add AsyncGenerator to the check-list of `dependencies.types.generator`
  .changeset/cute-ghosts-grab.md
  gradio/blocks.py
Labels: v: patch

#6347 Fix `colorFrom` in theme space readmes
  .changeset/late-donuts-warn.md
  gradio/themes/utils/readme_content.py
Labels: v: patch

#6356 Redesign file upload
  .changeset/proud-flies-serve.md
  js/upload/src/Upload.svelte
  js/upload/src/UploadProgress.svelte
Labels: v: patch

#6363 Fix image upload
  .changeset/olive-baboons-divide.md
  js/image/Index.svelte
Labels: v: patch

#6368 Fix component update bug
  .changeset/early-geese-relate.md
  gradio/component_meta.py
  test/test_blocks.py
Labels: v: patch

#6331 chore: update versions
  .changeset/clean-lands-follow.md
  .changeset/cute-ghosts-grab.md
  .changeset/early-geese-relate.md
  .changeset/fresh-months-bake.md
  .changeset/late-donuts-warn.md
  .changeset/olive-baboons-divide.md
  .changeset/proud-flies-serve.md
  .changeset/ready-dancers-camp.md
  .changeset/red-ties-turn.md
  .changeset/tired-berries-tease.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/textbox/CHANGELOG.md
  js/textbox/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
Labels: no-visual-update

#6378 Allows `sources` to be a string for `gr.Image`
  .changeset/eleven-windows-relate.md
  gradio/components/audio.py
  gradio/components/image.py
  gradio/components/video.py
  test/test_components.py
Labels: v: minor

#6382 Move wavesurfer dep to js/audio
  .changeset/hot-coins-rescue.md
  js/audio/package.json
  package.json
  pnpm-lock.yaml
  test/test_gradio_component_cli.py
Labels: v: patch

#6403 Remove websockets dependency
  .changeset/deep-cycles-switch.md
  requirements.txt
Labels: v: patch

#6395 Async functions and async generator functions with the `every` option to work
  .changeset/cold-gifts-tickle.md
  gradio/utils.py
  test/test_utils.py
Labels: v: patch

#6412 Added docs on gr.Examples
  .changeset/chubby-clowns-refuse.md
  gradio/CHANGELOG.md
  gradio/helpers.py
  guides/03_building-with-blocks/01_blocks-and-event-listeners.md
Labels: v: patch

#6381 chore: update versions
  .changeset/busy-suns-mate.md
  .changeset/chubby-clowns-refuse.md
  .changeset/cold-gifts-tickle.md
  .changeset/deep-cycles-switch.md
  .changeset/dirty-wasps-divide.md
  .changeset/eager-swans-tan.md
  .changeset/eleven-windows-relate.md
  .changeset/hot-coins-rescue.md
  .changeset/itchy-doors-work.md
  .changeset/light-symbols-know.md
  .changeset/neat-swans-obey.md
  .changeset/shaggy-states-swim.md
  .changeset/spotty-cameras-shop.md
  .changeset/strong-bars-cross.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  js/wasm/CHANGELOG.md
  js/wasm/package.json
  pnpm-lock.yaml
Labels: no-visual-update, windows-tests

#6419 Add download tests for audio/video
  .changeset/true-garlics-report.md
  demo/audio_component_events/run.ipynb
  demo/audio_component_events/run.py
  gradio/components/audio.py
  js/app/test/audio_component_events.spec.ts
  js/app/test/video_component_events.spec.ts
  js/audio/static/StaticAudio.svelte
Labels: v: patch

#6437 chore: rename api_key to hf_token
  .changeset/violet-mammals-cut.md
  demo/autocomplete/run.ipynb
  demo/autocomplete/run.py
  demo/automatic-speech-recognition/run.ipynb
  demo/automatic-speech-recognition/run.py
  gradio/external.py
Labels: no-visual-update

#6428 Extract video filenames correctly from URLs
  .changeset/afraid-bags-lose.md
  gradio/components/video.py
  gradio/utils.py
  test/test_utils.py
Labels: v: patch

#6455 Add py.typed to gradio backend
  .changeset/fast-cities-build.md
  .gitignore
  gradio/templates.py
  pyproject.toml
  scripts/type_check_backend.sh
Labels: v: patch

#6456 Preserve original image extension in backend processing
  .changeset/rotten-results-judge.md
  gradio/components/image.py
  gradio/image_utils.py
  gradio/processing_utils.py
  js/app/test/image_component_events.spec.ts
Labels: v: patch

#6467 Fix dev mode
  .changeset/kind-papayas-push.md
  js/preview/src/examine.py
Labels: v: patch

#6472 chore: update versions
  .changeset/deep-jokes-brush.md
  .changeset/kind-papayas-push.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/preview/CHANGELOG.md
  js/preview/package.json
Labels: no-visual-update, windows-tests

#6502 Ensure image editor crop and draw cursor works as expected when the scroll position changes
  .changeset/whole-buckets-add.md
  gradio/components/image_editor.py
  js/imageeditor/shared/ImageEditor.svelte
Labels: v: patch, t: fix

#6511 Mark `FileData.orig_name` optional on the frontend aligning the type definition on the Python side
  .changeset/cruel-pandas-design.md
  client/js/src/upload.ts
  js/file/shared/utils.ts
Labels: v: patch

#6538 Some tweaks to `ImageEditor`
  .changeset/real-things-push.md
  CHANGELOG.md
  gradio/components/image_editor.py
  gradio/templates.py
Labels: v: patch

#6554 chore: update versions
  .changeset/five-experts-repeat.md
  .changeset/slow-books-like.md
  .changeset/stupid-brooms-cut.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/markdown/CHANGELOG.md
  js/markdown/package.json
  js/preview/CHANGELOG.md
  js/preview/package.json
Labels: no-visual-update, windows-tests
