Repository gradio-app/gradio, pull requests merged in 2023-07, with the labels that each got.

#4740 Minor tweaks to API page UI
  js/app/src/api_docs/ApiBanner.svelte
  js/app/src/api_docs/ApiDocs.svelte
Labels: no-changelog-update

#4772 Add docs for `autoplay` parameter
  gradio/components/audio.py
  gradio/components/chatbot.py
  gradio/components/video.py
Labels: no-changelog-update

#4777 Fix code render in key features
  guides/01_getting-started/02_key-features.md
Labels: no-changelog-update

#4747 Add 'pnpm --filter @gradio/client build' to the build script of @gradio/lite
  js/app/package.json
Labels: no-changelog-update

#4753 Lite: refactoring the dev script
  js/app/package.json
  js/wasm/package.json
Labels: no-changelog-update

#4745 chatbot unit tests
  js/app/src/components/Chatbot/Chatbot.test.ts
  js/chatbot/src/ChatBot.svelte
Labels: no-changelog-update

#4787 Fix changelog issues in website
  CHANGELOG.md
Labels: no-changelog-update

#4749 ClearButton browser test
  demo/clear_components/__init__.py
  demo/clear_components/run.ipynb
  demo/clear_components/run.py
  demo/reset_components/run.py
  js/app/test/clear_components.spec.ts
  scripts/copy_demos.py
  website/homepage/upload_demos.py
Labels: no-changelog-update

#4784 Fix/lite dev code
  .changeset/proud-panthers-kneel.md
  js/app/lite.html
  js/app/src/lite/index.ts
Labels: no-changelog-update, no-visual-update

#4744 4701 upload button unit tests
  js/app/src/components/UploadButton/UploadButton.svelte
  js/app/src/components/UploadButton/UploadButton.test.ts
  js/upload-button/src/UploadButton.svelte
Labels: no-changelog-update, no-visual-update

#4752 Adds more tests to `outbreak_forecast.spec.ts`
  js/app/test/outbreak_forecast.spec.ts
  js/plot/src/Plot.svelte
Labels: no-changelog-update

#4794 unit tests for shared component functionality
  .config/playwright.config.js
  js/app/src/components/Label/Label.svelte
  js/app/test/components.test.ts
  js/app/test/tests.md
  js/app/vite.config.ts
  js/button/src/Button.svelte
  js/wasm/src/webworker/file.test.ts
  js/wasm/src/webworker/requirements.test.ts
  package.json
Labels: no-changelog-update, no-visual-update

#4788 Prebuild lite css
  .changeset/happy-plums-sing.md
  .github/workflows/ui.yml
  js/app/.gitignore
  js/app/lite.html
  js/app/package.json
  js/app/src/lite/css.ts
  js/app/src/lite/index.ts
  scripts/generate_theme.py
Labels: no-changelog-update

#4785 Lite: Add methods to run Python files mounted on a virtual file system, and unmount() method
  .changeset/large-items-reflect.md
  .changeset/smooth-ways-battle.md
  js/app/src/lite/index.ts
  js/lite/index.html
  js/wasm/src/message-types.ts
  js/wasm/src/webworker/index.ts
  js/wasm/src/webworker/py/.editorconfig
  js/wasm/src/webworker/py/script_runner.py
  js/wasm/src/worker-proxy.ts
Labels: no-changelog-update

#4810 format
  .config/.prettierrc.json
  .config/playwright-setup.js
  .config/playwright/index.html
  client/js/src/client.ts
  client/js/src/utils.ts
  js/_cdn-test/index.html
  js/_spaces-test/src/app.html
  js/_website/package.json
  js/_website/postcss.config.cjs
  js/_website/src/app.d.ts
  js/_website/src/app.html
  js/_website/src/assets/copy.js
  js/_website/src/assets/demo_code.js
  js/_website/src/assets/index.ts
  js/_website/src/assets/prism.css
  js/_website/src/assets/style.css
  js/_website/src/assets/tweets.json
  js/_website/src/components/clickOutside.ts
  js/_website/src/params/valid_doc.ts
  js/_website/src/params/valid_guide.ts
  js/_website/src/routes/+layout.server.ts
  js/_website/src/routes/+page.server.ts
  js/_website/src/routes/changelog/+page.server.ts
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/demos/+page.server.ts
  js/_website/src/routes/demos/demos.json
  js/_website/src/routes/docs/+page.server.ts
  js/_website/src/routes/docs/[doc=valid_doc]/+page.server.ts
  js/_website/src/routes/docs/block-layouts/+page.server.ts
  js/_website/src/routes/docs/combining-interfaces/+page.server.ts
  js/_website/src/routes/docs/components/+page.server.ts
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/docs/flagging/+page.server.ts
  js/_website/src/routes/docs/js-client/+page.server.ts
  js/_website/src/routes/docs/python-client/+page.server.ts
  js/_website/src/routes/docs/themes/+page.server.ts
  js/_website/src/routes/redirects.js
  js/_website/src/routes/version.json
  js/_website/svelte.config.js
  js/_website/tailwind.config.cjs
  js/_website/tsconfig.json
  js/_website/vercel.json
  js/_website/vite.config.ts
  js/app/build_plugins.ts
  js/app/index.html
  js/app/lite.html
  js/app/src/components/Chatbot/Chatbot.test.ts
  js/app/src/lite/css.ts
  js/app/src/lite/index.ts
  js/app/test/cancel_events.spec.ts
  js/app/test/chatbot_multimodal.spec.ts
  js/app/test/outbreak_forecast.spec.ts
  js/lite/index.html
  js/plot/package.json
  js/wasm/src/cross-origin-worker.ts
  js/wasm/src/webworker/index.ts
  js/wasm/src/worker-proxy.ts
  package.json
Labels: no-changelog-update

#4818 Add storybook for Gallery
  js/app/src/components/Gallery/Gallery.stories.svelte
Labels: no-changelog-update

#4816 Install gradio from source for chromatic
  .github/workflows/ui.yml
Labels: no-changelog-update

#4823 Fix gr.Warning/gr.Info when using generators + interface
  demo/blocks_chained_events/run.ipynb
  demo/blocks_chained_events/run.py
  gradio/interface.py
  js/app/test/blocks_chained_events.spec.ts
  test/test_blocks.py
Labels: no-changelog-update

#4815 Release v3.36.0
  CHANGELOG.md
  gradio/version.txt
Labels: no-changelog-update

#4819 Add gr.ClearButton component demo
  demo/clearbutton_component/run.ipynb
  demo/clearbutton_component/run.py
  js/app/src/components/Gallery/Gallery.stories.svelte
Labels: no-changelog-update

#4828 Fix Changelog Navbar in Website
  js/_website/src/app.html
  js/_website/src/routes/changelog/+page.server.ts
  js/_website/src/routes/changelog/+page.svelte
Labels: no-changelog-update

#4832 Fix Misleading Description for Duplicate Button
  gradio/components/duplicate_button.py
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/demos/demos.json
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/version.json
Labels: no-changelog-update

#4830 Fix broken images in guides and website meta tags
  guides/01_getting-started/02_key-features.md
  guides/01_getting-started/03_sharing-your-app.md
  js/_website/src/components/MetaTags.svelte
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/guides/json/key-features.json
  js/_website/src/routes/guides/json/sharing-your-app.json
Labels: no-changelog-update

#4809 Lite: PoC of an online editor
  js/app/lite.html
  js/app/src/lite/dev/App.svelte
  js/app/src/lite/index.ts
Labels: no-changelog-update

#4824 Update .prettierignore
  .config/.prettierignore
Labels: no-changelog-update

#4846 Lite: Fix the markdown-it package name spec on the Wasm worker
  .changeset/spicy-fishes-taste.md
  js/wasm/src/webworker/index.ts
Labels: no-changelog-update, no-visual-update

#4860 Quick update for the docstring in `gr.Chatbot`
  gradio/components/chatbot.py
Labels: no-changelog-update

#4852 Remove an unnecessary line of .prettierignore
  .config/.prettierignore
Labels: no-changelog-update

#4861 Bump version of python client
  client/python/CHANGELOG.md
  client/python/gradio_client/version.txt
Labels: no-changelog-update

#4863 Fix component events matrix in docs
  gradio/events.py
  js/_website/generate_jsons/src/docs/__init__.py
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/docs/components/+page.server.ts
  js/_website/src/routes/docs/components/+page.svelte
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/docs/js-client/+page.server.ts
  js/_website/src/routes/docs/js-client/+page.svelte
  js/_website/src/routes/docs/python-client/+page.server.ts
  js/_website/src/routes/docs/python-client/+page.svelte
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/redirects.js
  js/_website/src/routes/version.json
Labels: no-changelog-update

#4864 Fix flaky e2e test
  js/app/test/blocks_chained_events.spec.ts
Labels: no-changelog-update

#4877 Fix path to gradio.svg in website
  js/_website/static/assets/gradio.svg
Labels: no-changelog-update

#4870 Quick fixes to video test
  test/test_components.py
Labels: testing, no-changelog-update

#4879 Lint website
  .config/.prettierignore
  js/_website/src/app.html
  js/_website/src/routes/+layout.server.ts
  js/_website/src/routes/changelog/+page.server.ts
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/demos/demos.json
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/docs/js-client/+page.server.ts
  js/_website/src/routes/version.json
  js/_website/vercel.json
  js/wasm/src/webworker/index.ts
Labels: no-changelog-update

#4890 add wheel install instructions to PR comment
  .github/workflows/deploy-pr-to-spaces.yml
Labels: no-changelog-update

#4892 update pr comment
  .github/workflows/deploy-pr-to-spaces.yml
Labels: no-changelog-update, no-visual-update

#4893 update pr comment
  .github/workflows/deploy-pr-to-spaces.yml
Labels: no-changelog-update

#4886 Fix loading spaces with api_name=False
  client/python/CHANGELOG.md
  client/python/gradio_client/client.py
  client/python/gradio_client/version.txt
  client/python/test/test_client.py
Labels: no-visual-update

#4906 Fix flaky ui test
  .config/playwright.config.js
  .github/workflows/ui.yml
  js/app/test/blocks_chained_events.spec.ts
  package.json
Labels: no-changelog-update, no-visual-update

#4904 Fix bug related to preprocessing URLs for video
  CHANGELOG.md
  gradio/components/audio.py
  gradio/components/video.py
  requirements.txt
  test/test_components.py
Labels: no-visual-update

#4913 Add gr.Group to docs
  .github/workflows/deploy-chromatic.yml
  js/_website/src/routes/docs/block-layouts/+page.server.ts
Labels: no-changelog-update

#4900 move all of the chatbot component in to js/chatbot
  js/app/src/components/Chatbot/index.ts
  js/app/test/components.test.ts
  js/chatbot/package.json
  js/chatbot/src/Chatbot.test.ts
  js/chatbot/src/Index.svelte
  js/chatbot/src/index.ts
  js/chatbot/src/static/ChatBot.svelte
  js/chatbot/src/static/Copy.svelte
  js/chatbot/src/static/MarkdownCode.svelte
  js/chatbot/src/static/autorender.d.ts
  js/chatbot/src/static/index.ts
  js/chatbot/src/utils.ts
  package.json
Labels: no-changelog-update

#4923 remove three types
  package.json
  pnpm-lock.yaml
  test.md
Labels: no-changelog-update

#4938 remove-file
  test.md
Labels: no-changelog-update, no-visual-update

#4947 Release 3.37
  CHANGELOG.md
  gradio/version.txt
  js/chatbot/src/static/ChatBot.svelte
Labels: no-changelog-update

#4952 Fix website using wrong gradio.js version
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/creating-a-chatbot-fast.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/version.json
Labels: no-changelog-update

#4781 chore: update versions
  .changeset/happy-plums-sing.md
  .changeset/large-items-reflect.md
  .changeset/mean-birds-cheer.md
  .changeset/proud-ears-teach.md
  .changeset/proud-panthers-kneel.md
  .changeset/smooth-ways-battle.md
  .changeset/spicy-fishes-taste.md
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-changelog-update

#4961 Quick fix for langchain, openai examples in Guide
  guides/04_chatbots/01_creating-a-chatbot-fast.md
Labels: no-changelog-update

#4833 Fix responsive issues with docs, guides and changelog
  js/_website/src/routes/changelog/+page.svelte
  js/_website/src/routes/docs/[doc=valid_doc]/+page.svelte
  js/_website/src/routes/docs/block-layouts/+page.svelte
  js/_website/src/routes/docs/combining-interfaces/+page.svelte
  js/_website/src/routes/docs/components/+page.svelte
  js/_website/src/routes/docs/flagging/+page.svelte
  js/_website/src/routes/docs/js-client/+page.svelte
  js/_website/src/routes/docs/python-client/+page.svelte
  js/_website/src/routes/docs/themes/+page.svelte
  js/_website/src/routes/guides/[guide=valid_guide]/+page.svelte
Labels: no-changelog-update

#4984 Quick fix to chat interface code example
  guides/04_chatbots/01_creating-a-chatbot-fast.md
Labels: no-changelog-update

#4991 Release 3.38
  CHANGELOG.md
  gradio/chat_interface.py
  gradio/themes/base.py
  gradio/themes/default.py
  gradio/version.txt
  js/chatbot/src/static/ChatBot.svelte
  scripts/copy_demos.py
  test/test_analytics.py
Labels: no-changelog-update

#4992 Revert "Add download button for audio"
  CHANGELOG.md
  gradio/components/audio.py
  js/app/src/components/Audio/Audio.svelte
  js/audio/src/StaticAudio.svelte
  test/test_components.py
Labels: no-changelog-update

#4994 Fix client changelog
  client/python/CHANGELOG.md
Labels: no-changelog-update

#4986 unified release process
  .changeset/changeset.cjs
  .changeset/config.json
  .changeset/fix_changelogs.cjs
  .config/eslint.config.js
  .github/workflows/generate-changeset.yml
  .github/workflows/publish-npm.yml
  .github/workflows/trigger-changeset.yml
  CHANGELOG.md
  build_pypi.sh
  client/js/package.json
  client/python/CHANGELOG.md
  client/python/build_pypi.sh
  client/python/gradio_client/package.json
  gradio/package.json
  js/accordion/package.json
  js/app/package.json
  js/atoms/package.json
  js/audio/package.json
  js/button/package.json
  js/chart/package.json
  js/chatbot/package.json
  js/code/package.json
  js/file/package.json
  js/form/package.json
  js/gallery/package.json
  js/highlighted-text/package.json
  js/html/package.json
  js/icons/package.json
  js/image/package.json
  js/json/package.json
  js/label/package.json
  js/markdown/package.json
  js/model3D/package.json
  js/plot/package.json
  js/table/README.md
  js/table/package.json
  js/tabs/package.json
  js/theme/package.json
  js/tooltip/package.json
  js/upload-button/package.json
  js/upload/package.json
  js/utils/package.json
  js/video/package.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  tsconfig.json
Labels: no-changelog-update

#4993 Revert "Revert "Add download button for audio""
  .changeset/ready-wombats-occur.md
  gradio/components/audio.py
  js/app/src/components/Audio/Audio.svelte
  js/audio/src/StaticAudio.svelte
  test/test_components.py
Labels: no-changelog-update

#5009 Correctly render changelog on website after new formatting
  .changeset/fruity-olives-beg.md
  js/_website/generate_jsons/src/changelog/__init__.py
  js/_website/src/routes/changelog/+page.server.ts
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/Gradio-and-Comet.json
  js/_website/src/routes/guides/json/Gradio-and-ONNX-on-Hugging-Face.json
  js/_website/src/routes/guides/json/Gradio-and-Wandb-Integration.json
  js/_website/src/routes/guides/json/creating-a-chatbot-fast.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/guides/json/running-gradio-on-your-web-server-with-nginx.json
  js/_website/src/routes/guides/json/sharing-your-app.json
  js/_website/src/routes/guides/json/theming-guide.json
  js/_website/vite.config.ts.timestamp-1690217423559-59574779b2a45.mjs
Labels: v: patch

#5007 Make sure tags aren't rendered inside a guide
  .changeset/ninety-papayas-pick.md
  guides/06_tabular-data-science-and-plots/01_connecting-to-a-database.md
  guides/06_tabular-data-science-and-plots/plot-component-for-maps.md
  guides/06_tabular-data-science-and-plots/using-gradio-for-tabular-workflows.md
  js/_website/generate_jsons/src/guides/__init__.py
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/Gradio-and-Comet.json
  js/_website/src/routes/guides/json/Gradio-and-ONNX-on-Hugging-Face.json
  js/_website/src/routes/guides/json/Gradio-and-Wandb-Integration.json
  js/_website/src/routes/guides/json/blocks-and-event-listeners.json
  js/_website/src/routes/guides/json/building-a-pictionary-app.json
  js/_website/src/routes/guides/json/connecting-to-a-database.json
  js/_website/src/routes/guides/json/create-your-own-friends-with-a-gan.json
  js/_website/src/routes/guides/json/creating-a-chatbot-fast.json
  js/_website/src/routes/guides/json/creating-a-custom-chatbot-with-blocks.json
  js/_website/src/routes/guides/json/creating-a-dashboard-from-bigquery-data.json
  js/_website/src/routes/guides/json/creating-a-dashboard-from-supabase-data.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/creating-a-realtime-dashboard-from-google-sheets.json
  js/_website/src/routes/guides/json/custom-interpretations-with-blocks.json
  js/_website/src/routes/guides/json/fastapi-app-with-the-gradio-client.json
  js/_website/src/routes/guides/json/getting-started-with-the-js-client.json
  js/_website/src/routes/guides/json/getting-started-with-the-python-client.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/guides/json/how-to-use-3D-model-component.json
  js/_website/src/routes/guides/json/image-classification-in-pytorch.json
  js/_website/src/routes/guides/json/image-classification-in-tensorflow.json
  js/_website/src/routes/guides/json/image-classification-with-vision-transformers.json
  js/_website/src/routes/guides/json/named-entity-recognition.json
  js/_website/src/routes/guides/json/plot-component-for-maps.json
  js/_website/src/routes/guides/json/real-time-speech-recognition.json
  js/_website/src/routes/guides/json/running-background-tasks.json
  js/_website/src/routes/guides/json/running-gradio-on-your-web-server-with-nginx.json
  js/_website/src/routes/guides/json/setting-up-a-demo-for-maximum-performance.json
  js/_website/src/routes/guides/json/theming-guide.json
  js/_website/src/routes/guides/json/using-blocks-like-functions.json
  js/_website/src/routes/guides/json/using-flagging.json
  js/_website/src/routes/guides/json/using-gradio-for-tabular-workflows.json
  js/_website/src/routes/guides/json/using-hugging-face-integrations.json
Labels: no-changelog-update, v: patch, t: fix

#4997 Add CSS resets and specifiers to play nice with HF blog
  .changeset/evil-mirrors-switch.md
  js/theme/src/reset.css
  js/theme/src/typography.css
Labels: no-changelog-update

#4960 Deploy ChatInterface as a discord bot
  .changeset/eleven-turkeys-talk.md
  client/python/gradio_client/cli/__init__.py
  client/python/gradio_client/cli/deploy_discord.py
  client/python/gradio_client/client.py
  client/python/gradio_client/templates/discord_chat.py
  client/python/gradio_client/version.txt
  gradio/cli.py
  guides/04_chatbots/03_creating-a-discord-bot-from-a-gradio-app.md
  requirements.txt
Labels: t: highlight

#5037 Correct gradio version on website
  .changeset/bumpy-bugs-rule.md
  js/_website/src/routes/changelog/changelog.json
  js/_website/src/routes/docs/docs.json
  js/_website/src/routes/guides/json/Gradio-and-Comet.json
  js/_website/src/routes/guides/json/Gradio-and-ONNX-on-Hugging-Face.json
  js/_website/src/routes/guides/json/Gradio-and-Wandb-Integration.json
  js/_website/src/routes/guides/json/building-a-pictionary-app.json
  js/_website/src/routes/guides/json/connecting-to-a-database.json
  js/_website/src/routes/guides/json/create-your-own-friends-with-a-gan.json
  js/_website/src/routes/guides/json/creating-a-dashboard-from-bigquery-data.json
  js/_website/src/routes/guides/json/creating-a-dashboard-from-supabase-data.json
  js/_website/src/routes/guides/json/creating-a-discord-bot-from-a-gradio-app.json
  js/_website/src/routes/guides/json/creating-a-new-component.json
  js/_website/src/routes/guides/json/creating-a-realtime-dashboard-from-google-sheets.json
  js/_website/src/routes/guides/json/custom-interpretations-with-blocks.json
  js/_website/src/routes/guides/json/developing-faster-with-reload-mode.json
  js/_website/src/routes/guides/json/fastapi-app-with-the-gradio-client.json
  js/_website/src/routes/guides/json/getting-started-with-the-js-client.json
  js/_website/src/routes/guides/json/getting-started-with-the-python-client.json
  js/_website/src/routes/guides/json/gradio-and-llm-agents.json
  js/_website/src/routes/guides/json/guide_names.json
  js/_website/src/routes/guides/json/guides_by_category.json
  js/_website/src/routes/guides/json/how-to-use-3D-model-component.json
  js/_website/src/routes/guides/json/image-classification-in-pytorch.json
  js/_website/src/routes/guides/json/image-classification-in-tensorflow.json
  js/_website/src/routes/guides/json/image-classification-with-vision-transformers.json
  js/_website/src/routes/guides/json/named-entity-recognition.json
  js/_website/src/routes/guides/json/plot-component-for-maps.json
  js/_website/src/routes/guides/json/real-time-speech-recognition.json
  js/_website/src/routes/guides/json/running-background-tasks.json
  js/_website/src/routes/guides/json/running-gradio-on-your-web-server-with-nginx.json
  js/_website/src/routes/guides/json/setting-up-a-demo-for-maximum-performance.json
  js/_website/src/routes/guides/json/theming-guide.json
  js/_website/src/routes/guides/json/using-flagging.json
  js/_website/src/routes/guides/json/using-gradio-for-tabular-workflows.json
  js/_website/src/routes/guides/json/using-hugging-face-integrations.json
  js/_website/src/routes/version.json
Labels: v: patch, t: fix
