Repository gradio-app/gradio, pull requests merged in 2023-12, with the labels that each got.

#6598 Issue 5245: consolidate usage of requests and httpx
  .changeset/tangy-cloths-look.md
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  client/python/requirements.txt
  client/python/test/test_client.py
  client/python/test/test_utils.py
  gradio/analytics.py
  gradio/blocks.py
  gradio/components/audio.py
  gradio/external.py
  gradio/external_utils.py
  gradio/networking.py
  gradio/processing_utils.py
  gradio/strings.py
  gradio/themes/base.py
  gradio/tunneling.py
  gradio/utils.py
  requirements.txt
  test/test_analytics.py
  test/test_components.py
  test/test_external.py
  test/test_helpers.py
  test/test_interfaces.py
  test/test_utils.py
Labels: v: patch

#6543 switch from black to ruff formatter
  .changeset/wise-feet-fold.md
  client/python/gradio_client/client.py
  client/python/gradio_client/documentation.py
  client/python/scripts/format.sh
  client/python/scripts/lint.sh
  client/python/test/requirements.txt
  client/python/test/test_utils.py
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/cli/commands/components/build.py
  gradio/cli/commands/components/create.py
  gradio/cli/commands/components/dev.py
  gradio/cli/commands/components/publish.py
  gradio/components/dataframe.py
  gradio/events.py
  gradio/external.py
  gradio/external_utils.py
  gradio/flagging.py
  gradio/helpers.py
  gradio/image_utils.py
  gradio/interface.py
  gradio/pipelines.py
  gradio/processing_utils.py
  gradio/route_utils.py
  gradio/templates.py
  gradio/themes/base.py
  gradio/themes/builder_app.py
  gradio/themes/default.py
  gradio/themes/glass.py
  gradio/themes/monochrome.py
  gradio/themes/soft.py
  gradio/utils.py
  scripts/format_backend.sh
  scripts/lint_backend.sh
  test/requirements.in
  test/requirements.txt
  test/test_components.py
  test/test_queueing.py
Labels: v: patch

#6432 Lite: Set the home dir path per appId at each runtime
  .changeset/true-terms-happen.md
  js/wasm/src/webworker/file.ts
  js/wasm/src/webworker/index.ts
  js/wasm/src/webworker/py/script_runner.py
Labels: gradio-lite

#6398 Lite v4
  .changeset/shiny-news-float.md
  client/js/src/client.ts
  gradio/components/video.py
  gradio/data_classes.py
  gradio/processing_utils.py
  js/app/src/lite/index.ts
  js/app/src/lite/sse.ts
  js/app/vite.config.ts
  js/audio/interactive/InteractiveAudio.svelte
  js/audio/player/AudioPlayer.svelte
  js/audio/static/StaticAudio.svelte
  js/code/package.json
  js/code/shared/Download.svelte
  js/file/package.json
  js/file/shared/FilePreview.svelte
  js/image/shared/Image.svelte
  js/image/shared/ImagePreview.svelte
  js/image/shared/ImageUploader.svelte
  js/video/shared/Video.svelte
  js/video/shared/VideoPreview.svelte
  js/wasm/src/asgi-types.ts
  js/wasm/src/http.ts
  js/wasm/src/index.ts
  js/wasm/src/message-types.ts
  js/wasm/src/messageportwebsocket.ts
  js/wasm/src/sse.ts
  js/wasm/src/webworker/asgi.ts
  js/wasm/src/webworker/http.ts
  js/wasm/src/webworker/index.ts
  js/wasm/src/webworker/websocket.ts
  js/wasm/src/worker-proxy.ts
  js/wasm/svelte/DownloadLink.svelte
  js/wasm/svelte/file-url.ts
  js/wasm/svelte/index.ts
  js/wasm/tsconfig.json
  pnpm-lock.yaml
Labels: gradio-lite

#6693 Python client properly handles hearbeat and log messages. Also handles responses longer than 65k
  .changeset/yummy-roses-decide.md
  client/js/src/client.ts
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  client/python/test/conftest.py
  client/python/test/test_client.py
  gradio/queueing.py
  gradio/routes.py
  test/test_queueing.py
Labels: v: patch

#6781 Fix backend tests on Windows
  .changeset/vast-kings-deny.md
  gradio/components/file_explorer.py
  test/test_components.py
Labels: v: patch, windows-tests

#6779 chore: update versions
  .changeset/modern-clubs-march.md
  .changeset/social-dancers-yawn.md
  .changeset/vast-kings-deny.md
  .changeset/yummy-roses-decide.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  client/python/CHANGELOG.md
  client/python/gradio_client/CHANGELOG.md
  client/python/gradio_client/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
  requirements.txt
Labels: no-visual-update, windows-tests

#6799 Adds docstrings for `gr.WaveformOptions`, `gr.Brush`, and `gr.Eraser`, fixes examples for `ImageEditor`, and allows individual images to be used as the initial `value` for `ImageEditor`
  .changeset/full-gifts-press.md
  gradio/__init__.py
  gradio/components/audio.py
  gradio/components/image_editor.py
  js/audio/player/AudioPlayer.svelte
  js/audio/recorder/AudioRecorder.svelte
  js/audio/shared/WaveformControls.svelte
  js/audio/shared/utils.ts
  js/imageeditor/Example.svelte
  js/imageeditor/ImageEditor.stories.svelte
  js/imageeditor/shared/tools/Brush.svelte
  pnpm-lock.yaml
  test/test_components.py
Labels: v: patch

#6798 Improve how server/js client handle unexpected errors
  .changeset/dirty-experts-cry.md
  client/js/src/client.ts
  gradio/routes.py
Labels: v: patch

#6797 chore: update versions
  .changeset/dirty-experts-cry.md
  .changeset/full-gifts-press.md
  .changeset/rich-dragons-clap.md
  .changeset/seven-donkeys-itch.md
  .changeset/shy-pots-stare.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
Labels: no-visual-update, windows-tests

#6814 Refactor queue so that there are separate queues for each concurrency id
  .changeset/eighty-teeth-greet.md
  client/js/src/client.ts
  gradio/blocks.py
  gradio/data_classes.py
  gradio/queueing.py
  gradio/routes.py
  js/statustracker/static/index.svelte
Labels: v: patch

#6846 Add `show_api` parameter to events, and fix `gr.load()`. Also makes some minor improvements to the "view API" page when running on Spaces
  .changeset/shaky-peaches-try.md
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
  demo/load_space/run.ipynb
  demo/load_space/run.py
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/component_meta.py
  gradio/components/clear_button.py
  gradio/events.py
  gradio/external.py
  gradio/helpers.py
  gradio/interface.py
  gradio/themes/builder_app.py
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/CodeSnippets.svelte
  js/app/src/api_docs/utils.ts
  js/app/src/types.ts
  js/app/test/load_space.spec.ts
  pnpm-lock.yaml
  test/test_api_info.py
  test/test_blocks.py
Labels: v: minor

#6855 chore: update versions
  .changeset/bumpy-baths-agree.md
  .changeset/lemon-waves-smash.md
  .changeset/nine-forks-raise.md
  .changeset/quick-chairs-check.md
  .changeset/quick-sites-send.md
  .changeset/shaky-peaches-try.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  client/python/CHANGELOG.md
  client/python/gradio_client/CHANGELOG.md
  client/python/gradio_client/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
  requirements.txt
Labels: no-visual-update, windows-tests

#6887 Fix the Wasm worker to initialize the app directories
  .changeset/tender-parks-change.md
  js/wasm/src/webworker/index.ts
Labels: v: patch

#6778 Add a dev instruction for lite in SharedWorker mode
  .changeset/busy-jobs-exist.md
  js/app/src/lite/dev/App.svelte
Labels: gradio-lite

#6870 Adding instructions on how to build Gradio-Lite locally
  CONTRIBUTING.md
  scripts/build_lite.sh
  scripts/helpers.sh
  scripts/run_lite.sh
Labels: v: patch

#6820 Use `EventSource_factory` in `open_stream()` for Wasm
  .changeset/short-clowns-deny.md
  client/js/src/client.ts
Labels: gradio-lite
