Repository gradio-app/gradio, pull requests merged in 2023-10, with the labels that each got.

#5755 Fix new line issue in chatbot
  .changeset/green-pillows-flash.md
  gradio/components/chatbot.py
  gradio/components/dataframe.py
  gradio/components/markdown.py
  js/chatbot/static/ChatBot.svelte
  js/chatbot/static/StaticChatbot.svelte
  js/dataframe/interactive/InteractiveDataframe.svelte
  js/dataframe/shared/EditableCell.svelte
  js/dataframe/shared/Table.svelte
  js/dataframe/static/StaticDataframe.svelte
  js/markdown/static/Markdown.svelte
  js/markdown/static/MarkdownCode.svelte
  js/markdown/static/StaticMarkdown.svelte
  js/markdown/static/utils.ts
  test/test_components.py
  test/test_files/xray_config.json
  test/test_files/xray_config_diff_ids.json
  test/test_files/xray_config_wrong.json
Labels: v: minor

#5672 Add component <-> server direct communication support, as well as a "file explorer" component
  .changeset/itchy-radios-pay.md
  client/js/src/client.ts
  client/python/gradio_client/serializing.py
  demo/file_explorer/run.ipynb
  demo/file_explorer/run.py
  gradio/__init__.py
  gradio/blocks.py
  gradio/components/__init__.py
  gradio/components/base.py
  gradio/components/file_explorer.py
  gradio/data_classes.py
  gradio/routes.py
  gradio/state_holder.py
  js/app/package.json
  js/app/src/Blocks.svelte
  js/app/src/components/Dataset/Dataset.svelte
  js/app/src/components/Dataset/directory.ts
  js/app/src/components/directory.ts
  js/code/static/StaticCode.svelte
  js/file/static/index.ts
  js/fileexplorer/example/File.svelte
  js/fileexplorer/example/index.ts
  js/fileexplorer/icons/light-file.svg
  js/fileexplorer/interactive/InteractiveFileExplorer.svelte
  js/fileexplorer/interactive/index.ts
  js/fileexplorer/package.json
  js/fileexplorer/shared/ArrowIcon.svelte
  js/fileexplorer/shared/Checkbox.svelte
  js/fileexplorer/shared/DirectoryExplorer.svelte
  js/fileexplorer/shared/FileTree.svelte
  js/fileexplorer/shared/index.ts
  js/fileexplorer/shared/utils.test.ts
  js/fileexplorer/shared/utils.ts
  js/fileexplorer/static/StaticFileExplorer.svelte
  js/fileexplorer/static/index.ts
  js/fileexplorer/static/utils.ts
  js/slider/Slider.stories.svelte
  js/theme/src/reset.css
  pnpm-lock.yaml
  test/test_blocks.py
Labels: t: highlight

#5816 Fix calls to the component server so that `gr.FileExplorer` works on Spaces
  .changeset/seven-months-divide.md
  client/js/src/client.ts
  client/js/src/utils.ts
  demo/file_explorer_component/run.ipynb
  demo/file_explorer_component/run.py
  gradio/components/file_explorer.py
Labels: v: patch, t: fix

#5817 chore: update versions
  .changeset/seven-months-divide.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
Labels: no-visual-update

#5822 Convert async methods in the Examples class into normal sync methods
  .changeset/evil-berries-teach.md
  gradio/helpers.py
  test/test_chat_interface.py
  test/test_helpers.py
Labels: v: patch, t: fix

#5811 Assert refactor in external.py
  .changeset/light-buses-enter.md
  client/python/gradio_client/client.py
  client/python/gradio_client/documentation.py
  client/python/gradio_client/exceptions.py
  client/python/gradio_client/serializing.py
  demo/clustering/run.ipynb
  demo/clustering/run.py
  gradio/blocks.py
  gradio/components/chatbot.py
  gradio/components/code.py
  gradio/components/dataframe.py
  gradio/components/dataset.py
  gradio/components/video.py
  gradio/exceptions.py
  gradio/external.py
  gradio/helpers.py
  gradio/interface.py
  gradio/interpretation.py
  gradio/queueing.py
  gradio/ranged_response.py
  gradio/utils.py
  test/test_utils.py
Labels: v: patch, t: fix

#5862 Remove deprecated `.update()` usage from Interface internals
  .changeset/spicy-cycles-send.md
  gradio/flagging.py
  gradio/interface.py
  gradio/themes/builder_app.py
Labels: v: patch

#5886 Lite: Fix is_self_host() to detect `127.0.0.1` as localhost as well
  .changeset/eager-snakes-look.md
  js/app/src/lite/url.ts
Labels: v: patch

#5919 Lite: Add a break statement
  .changeset/all-crabs-doubt.md
  js/wasm/src/webworker/index.ts
Labels: v: patch, t: fix

#5925 Reinstate types that were removed in error in #5832.
  .changeset/two-games-dress.md
  js/app/src/Blocks.svelte
  js/app/src/Index.svelte
  js/app/src/Render.svelte
  js/app/src/main.ts
  js/app/src/types.ts
  js/app/src/vite-env-override.d.ts
Labels: t: fix

#5976 chore: update versions
  .changeset/fast-readers-feel.md
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update

#5981 chore: update versions
  .changeset/eight-hoops-juggle.md
  .changeset/red-terms-rest.md
  .changeset/serious-pears-tell.md
  .changeset/shy-ghosts-turn.md
  .changeset/warm-chefs-trade.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  js/wasm/CHANGELOG.md
  js/wasm/package.json
Labels: no-visual-update

#5992 chore: update versions
  .changeset/brave-readers-notice.md
  .changeset/chatty-laws-drop.md
  .changeset/few-items-float.md
  .changeset/open-kids-dance.md
  .changeset/wet-dingos-battle.md
  .changeset/wise-hands-dress.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  js/wasm/CHANGELOG.md
  js/wasm/package.json
Labels: no-visual-update

#6032 fix main entrypoint
  .changeset/dry-kiwis-attend.md
  js/lite/package.json
Labels: v: patch, t: fix

#6025 chore: update versions
  .changeset/dry-kiwis-attend.md
  .changeset/whole-women-clean.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update

#6065 fix storybook
  .changeset/every-cities-invite.md
  .github/workflows/deploy-chromatic.yml
  js/app/src/Login.stories.svelte
  js/app/src/Login.svelte
  js/dataframe/Dataframe.stories.svelte
  js/dropdown/Dropdown.stories.svelte
  js/dropdown/Multiselect.stories.svelte
  js/dropdown/shared/Dropdown.svelte
  js/gallery/Gallery.stories.svelte
  js/highlightedtext/HighlightedText.stories.svelte
  js/image/Image.stories.svelte
  js/row/Row.stories.svelte
  js/storybook/preview.ts
Labels: v: patch, t: fix

#6067 remove dupe component
  .changeset/chilly-dodos-serve.md
  js/video/shared/Player.svelte
  js/video/shared/StaticVideo.svelte
  tsconfig.json
Labels: v: patch, t: fix

#6044 Simplify File Component
  .changeset/true-flowers-hug.md
  .config/playwright/index.html
  gradio/cli/commands/components/show.py
  js/file/Index.svelte
  js/file/shared/FileUpload.svelte
  js/image/package.json
  js/tootils/package.json
  js/upload/src/Upload.svelte
  js/upload/src/index.ts
  js/upload/src/utils.ts
  js/uploadbutton/Index.svelte
  js/uploadbutton/shared/UploadButton.svelte
Labels: v: patch

#6114 Try to trigger a major beta release
  .changeset/poor-lands-talk.md
  pyproject.toml
Labels: v: major

#6146 Fix image double change bug
  .changeset/cool-ties-mix.md
  js/image/Index.svelte
  js/image/shared/ImagePreview.svelte
Labels: v: patch, t: fix

#6148 fix dropdown arrow size
  .changeset/lovely-rocks-cut.md
  js/dropdown/shared/Dropdown.svelte
  js/dropdown/shared/Multiselect.svelte
Labels: v: patch, t: fix

#6189 Custom Component Guides
  .changeset/gentle-hounds-invite.md
  guides/05_custom-components/01_five-minute-guide.md
  guides/05_custom-components/02_key-component-concepts.md
  guides/05_custom-components/03_configuration.md
  guides/05_custom-components/04_backend.md
  guides/05_custom-components/05_frontend.md
  guides/05_custom-components/06_frequently-asked-questions.md
  guides/06_integrating-other-frameworks/01_using-hugging-face-integrations.md
  guides/06_integrating-other-frameworks/Gradio-and-Comet.md
  guides/06_integrating-other-frameworks/Gradio-and-ONNX-on-Hugging-Face.md
  guides/06_integrating-other-frameworks/Gradio-and-Wandb-Integration.md
  guides/06_integrating-other-frameworks/image-classification-in-pytorch.md
  guides/06_integrating-other-frameworks/image-classification-in-tensorflow.md
  guides/06_integrating-other-frameworks/image-classification-with-vision-transformers.md
  guides/07_tabular-data-science-and-plots/01_connecting-to-a-database.md
  guides/07_tabular-data-science-and-plots/creating-a-dashboard-from-bigquery-data.md
  guides/07_tabular-data-science-and-plots/creating-a-dashboard-from-supabase-data.md
  guides/07_tabular-data-science-and-plots/creating-a-realtime-dashboard-from-google-sheets.md
  guides/07_tabular-data-science-and-plots/plot-component-for-maps.md
  guides/07_tabular-data-science-and-plots/styling-the-gradio-dataframe.md
  guides/07_tabular-data-science-and-plots/using-gradio-for-tabular-workflows.md
  guides/08_client-libraries/01_getting-started-with-the-python-client.md
  guides/08_client-libraries/02_getting-started-with-the-js-client.md
  guides/08_client-libraries/fastapi-app-with-the-gradio-client.md
  guides/08_client-libraries/gradio-and-llm-agents.md
  guides/09_other-tutorials/building-a-pictionary-app.md
  guides/09_other-tutorials/create-your-own-friends-with-a-gan.md
  guides/09_other-tutorials/creating-a-new-component.md
  guides/09_other-tutorials/custom-interpretations-with-blocks.md
  guides/09_other-tutorials/developing-faster-with-reload-mode.md
  guides/09_other-tutorials/gradio-lite.md
  guides/09_other-tutorials/how-to-use-3D-model-component.md
  guides/09_other-tutorials/named-entity-recognition.md
  guides/09_other-tutorials/real-time-speech-recognition.md
  guides/09_other-tutorials/running-background-tasks.md
  guides/09_other-tutorials/running-gradio-on-your-web-server-with-nginx.md
  guides/09_other-tutorials/setting-up-a-demo-for-maximum-performance.md
  guides/09_other-tutorials/theming-guide.md
  guides/09_other-tutorials/using-flagging.md
  js/_website/generate_jsons/src/guides/__init__.py
  js/_website/src/lib/assets/style.css
  js/_website/src/routes/[[version]]/docs/js-client/+page.server.ts
  js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
Labels: v: patch

#6188 chore: update versions
  .changeset/gentle-hounds-invite.md
  .changeset/shaky-peaches-spend.md
  .changeset/short-doodles-lose.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
Labels: no-visual-update

#6191 fix cdn build
  .changeset/moody-rooms-sleep.md
  js/app/build_plugins.ts
  js/app/vite.config.ts
  js/preview/rollup.config.js
  package.json
Labels: v: patch, t: fix

#6192 chore: update versions
  .changeset/moody-rooms-sleep.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/preview/CHANGELOG.md
  js/preview/package.json
Labels: no-visual-update
