Repository gradio-app/gradio, pull requests merged in 2023-09, with the labels that each got.

#5391 Like/Dislike Button for Chatbot
  .changeset/gold-garlics-cut.md
  gradio/__init__.py
  gradio/components/chatbot.py
  gradio/events.py
  guides/04_chatbots/02_creating-a-custom-chatbot-with-blocks.md
  js/chatbot/Chatbot.test.ts
  js/chatbot/static/ChatBot.svelte
  js/chatbot/static/StaticChatbot.svelte
  js/icons/src/Dislike.svelte
  js/icons/src/Like.svelte
  js/icons/src/index.ts
  js/markdown/Markdown.stories.svelte
  js/utils/src/utils.ts
  test/test_components.py
Labels: t: highlight

#5412 Skip view_api request in js client when auth enabled
  .changeset/silent-otters-brake.md
  client/js/src/client.ts
Labels: t: fix

#5445 ensure dataframe doesn't scroll unless needed
  .changeset/chatty-socks-bow.md
  js/dataframe/shared/VirtualTable.svelte
Labels: v: patch, t: fix

#5447 ensure iframe is correct size on spaces
  .changeset/six-months-act.md
  js/app/index.html
  js/app/src/Embed.svelte
Labels: v: patch, t: fix

#5500 release first version
  .changeset/cold-hoops-heal.md
  js/atoms/package.json
  js/column/package.json
  js/icons/package.json
  js/statustracker/package.json
  js/tooltip/package.json
  js/upload/package.json
  js/utils/package.json
Labels: v: minor, t: feat

#5516 Fix docstring of dropdown
  .changeset/chubby-hats-type.md
  gradio/components/dropdown.py
Labels: v: patch

#5547 fix: typo in UploadButton's docstring
  .changeset/eager-wasps-move.md
  gradio/components/upload_button.py
Labels: v: patch

#5514 refactor: Use package.json for version management
  .changeset/fix_changelogs.cjs
  .changeset/smart-birds-drop.md
  .config/basevite.config.ts
  .github/workflows/build-pr.yml
  build_pypi.sh
  client/python/gradio_client/utils.py
  client/python/gradio_client/version.txt
  client/python/pyproject.toml
  client/python/scripts/check_pypi.py
  gradio/__init__.py
  gradio/analytics.py
  gradio/blocks.py
  gradio/routes.py
  gradio/utils.py
  gradio/version.txt
  js/app/vite.config.ts
  pyproject.toml
  scripts/check_pypi.py
  scripts/upload_website_demos.py
Labels: v: patch

#5535 Makes sliders consistent across all browsers
  .changeset/sour-mirrors-travel.md
  gradio/themes/base.py
  js/slider/Slider.stories.svelte
  js/slider/shared/Range.svelte
Labels: v: patch

#5534 Guide fixes, esp. streaming audio
  .changeset/long-kings-punch.md
  demo/asr/requirements.txt
  demo/asr/run.ipynb
  demo/asr/run.py
  demo/reversible_flow/run.ipynb
  demo/reversible_flow/run.py
  demo/stream_asr/requirements.txt
  demo/stream_asr/run.ipynb
  demo/stream_asr/run.py
  gradio/blocks.py
  gradio/events.py
  guides/01_getting-started/02_key-features.md
  guides/02_building-interfaces/04_advanced-interface-features.md
  guides/03_building-with-blocks/02_controlling-layout.md
  guides/06_tabular-data-science-and-plots/using-gradio-for-tabular-workflows.md
  guides/08_other-tutorials/real-time-speech-recognition.md
  guides/cn/01_getting-started/02_key-features.md
  guides/cn/03_building-with-blocks/02_controlling-layout.md
  guides/cn/05_tabular-data-science-and-plots/using-gradio-for-tabular-workflows.md
Labels: v: patch, t: fix

#5595 Hot fix for publishing bash script
  build_pypi.sh
Labels: t: fix

#5590 Attach `elem_classes` selectors to layout elements, and an id to the Tab button (for targeting via CSS/JS)
  .changeset/real-items-cover.md
  gradio/layouts.py
  js/tabitem/static/TabItem.svelte
  js/tabs/static/Tabs.svelte
  pnpm-lock.yaml
Labels: v: patch

#5598 Upgrade Pyodide to 0.24.0 and install the native orjson package
  .changeset/rich-points-dance.md
  gradio/routes.py
  js/wasm/src/webworker/index.ts
Labels: v: patch

#5635 Fix typos in Gallery docs
  .changeset/puny-papayas-bake.md
  gradio/components/gallery.py
Labels: v: patch

#5653 Prevent Clients from accessing API endpoints that set `api_name=False`
  .changeset/hip-chefs-share.md
  client/js/src/client.ts
  client/python/gradio_client/client.py
  client/python/test/test_client.py
Labels: v: patch

#5677 [Refactoring] Convert async functions that don't contain `await` statements to normal functions
  .changeset/famous-comics-fly.md
  gradio/blocks.py
  gradio/queueing.py
  test/test_queueing.py
Labels: v: patch

#5696 setting share=True on Spaces or in wasm should warn instead of raising error
  .changeset/young-glasses-juggle.md
  gradio/blocks.py
Labels: v: patch, t: fix

#5709 ensure client is copied along with components
  .changeset/bright-planes-divide.md
  .config/copy_frontend.py
Labels: v: patch

#5711 fix: prevent internal log_message error from `/api/predict`
  .changeset/sour-pillows-hug.md
  gradio/helpers.py
Labels: v: patch

#5668 Fully resolve generated filepaths when running on Hugging Face Spaces with multiple replicas
  .changeset/some-forks-raise.md
  gradio/route_utils.py
  gradio/routes.py
  test/test_route_utils.py
Labels: v: patch, t: fix

#5721 Adds copy buttons to website, and better descriptions to API Docs
  .changeset/wild-clowns-return.md
  client/python/gradio_client/serializing.py
  client/python/gradio_client/types.json
  client/python/test/test_client.py
  gradio/components/highlighted_text.py
  js/_website/src/lib/assets/prism.css
  js/_website/src/lib/assets/style.css
  js/_website/src/lib/components/CopyButton.svelte
  js/_website/src/lib/components/Demos.svelte
  js/_website/src/lib/components/DemosLanding.svelte
  js/_website/src/lib/components/FunctionDoc.svelte
  js/_website/src/routes/+layout.svelte
  js/_website/src/routes/[[version]]/docs/[doc]/+page.svelte
  js/_website/src/routes/[[version]]/docs/components/+page.svelte
  js/_website/src/routes/[[version]]/docs/flagging/+page.svelte
  js/_website/src/routes/[[version]]/docs/python-client/+page.svelte
  js/_website/src/routes/[[version]]/docs/themes/+page.svelte
  js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
  js/app/src/api_docs/CodeSnippets.svelte
  js/app/src/api_docs/ResponseObject.svelte
Labels: v: patch

#5722 Fix for deepcopy errors when running the replica-related logic on Spaces
  .changeset/true-candles-pay.md
  gradio/route_utils.py
  gradio/routes.py
  test/test_route_utils.py
Labels: v: patch

#5705 ensure internal data has updated before dispatching `success` or `then` events
  .changeset/rare-lines-show.md
  client/js/src/client.ts
  js/app/src/Blocks.svelte
Labels: v: patch, t: fix
