Repository gradio-app/gradio, pull requests merged in 2024-04, with the labels that each got.

#7850 Adds an "API Recorder" to the view API page, some internal methods have been made async
  .changeset/red-roses-hide.md
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
  gradio/blocks.py
  gradio/helpers.py
  gradio/processing_utils.py
  guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
  guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
  js/app/src/Blocks.svelte
  js/app/src/api_docs/ApiBanner.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/ApiRecorder.svelte
  js/app/src/api_docs/CodeSnippet.svelte
  js/app/src/api_docs/RecordingSnippet.svelte
  js/app/src/api_docs/index.ts
  js/app/src/api_docs/utils.ts
  test/test_blocks.py
  test/test_components.py
Labels: v: patch

#7912 Allow displaying gr.Code examples by their filename if value is a tuple
  .changeset/fast-walls-drop.md
  gradio/components/code.py
  test/test_components.py
Labels: v: patch

#7936 Restore Markdown formatting for Chatbots, MarkdownCode
  .changeset/eight-views-yawn.md
  js/chatbot/Chatbot.stories.svelte
  js/markdown/shared/MarkdownCode.svelte
  js/theme/src/typography.css
Labels: v: patch

#7938 Handle the case of multiple headers when constructing root url
  .changeset/little-breads-allow.md
  gradio/route_utils.py
  test/test_routes.py
Labels: v: patch

#7932 Use asyncio.Event to stop stream in heartbeat route
  .changeset/tiny-friends-stick.md
  gradio/blocks.py
  gradio/route_utils.py
  gradio/routes.py
  gradio/utils.py
  js/app/test/unload_event_test.spec.ts
Labels: v: patch

#7961 Fix task bug in python 3.9
  .changeset/twenty-paws-poke.md
  gradio/route_utils.py
Labels: v: patch

#7966 Adding hint `list[list]` for example parameter
  .changeset/honest-spiders-visit.md
  gradio/chat_interface.py
Labels: v: patch

#7887 When authenticating with HF OAuth, stay in same tab
  .changeset/poor-lands-hug.md
  gradio/components/code.py
  gradio/components/login_button.py
  gradio/oauth.py
  js/app/index.html
Labels: v: patch

#7974 Fix heartbeat in the js client to be Lite compatible
  .changeset/eighty-rockets-march.md
  client/js/src/client.ts
Labels: v: patch, t: fix, gradio-lite

#7981 Fix example loading for custom components
  .changeset/quiet-laws-joke.md
  demo/gradio_pdf_demo/contract.pdf
  demo/gradio_pdf_demo/requirements.txt
  demo/gradio_pdf_demo/run.ipynb
  demo/gradio_pdf_demo/run.py
  js/app/src/init.ts
  js/app/test/gradio_pdf_demo.spec.ts
  test/requirements.txt
Labels: v: patch, t: fix

#7986 GRADIO_SHARE Environment Variable
  .changeset/free-things-wink.md
  gradio/blocks.py
Labels: v: patch

#8002 Add show_progress prop to Upload Component to bring back upload progress animation
  .changeset/fair-trains-marry.md
  js/app/test/gradio_pdf_demo.spec.ts
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
  js/upload/src/Upload.svelte
Labels: v: patch, t: fix

#7998 Restore chatbot formatting
  .changeset/bright-ends-prove.md
  js/chatbot/shared/ChatBot.svelte
  js/theme/src/typography.css
Labels: v: patch

#8012 Document that show_copy_button in gr.Textbox is not visible when show_label=False
  .changeset/upset-coins-remain.md
  gradio/components/textbox.py
  test/test_helpers.py
Labels: v: patch

#8011 Add an explicit dependency of `urllib3~=2.0` and update `processing_utils.save_url_to_cache` to use `urllib3` for Lite support
  .changeset/nine-melons-follow.md
  gradio/processing_utils.py
  requirements.txt
  test/requirements.txt
Labels: v: minor, gradio-lite

#8000 Fix internal server error in HF OAuth workflow
  .changeset/many-symbols-arrive.md
  gradio/oauth.py
Labels: v: patch

#8028 ensure maps are correctly shallow cloned when updating state
  .changeset/eight-lights-jog.md
  demo/calculator_blocks/run.ipynb
  demo/calculator_blocks/run.py
  js/app/src/init.ts
  js/dataset/Index.svelte
Labels: v: patch, t: fix

#8026 Patch `async_save_url_to_cache` for Lite
  .changeset/silly-seals-care.md
  .config/playwright.config.js
  demo/image_remote_url/run.ipynb
  demo/image_remote_url/run.py
  gradio/processing_utils.py
  js/app/test/image_remote_url.spec.ts
Labels: v: patch, t: fix

#8050 Update `typer` to drop `[all]` as it is no longer needed
  .changeset/sour-queens-count.md
  requirements.txt
Labels: v: patch, t: fix

#8046 round [x, y, w, h] before cropping to avoid unexpected interpolation on pixel values
  .changeset/green-keys-invite.md
  js/imageeditor/shared/ImageEditor.svelte
Labels: v: patch, t: fix

#8063 Fix `gr.Label` styling and a11y markup
  .changeset/rotten-games-fly.md
  js/label/Label.stories.svelte
  js/label/shared/Label.svelte
Labels: v: patch

#8075 Fix causing Hot Reload (#8070)
  .changeset/easy-symbols-pick.md
  gradio/utils.py
Labels: v: patch, t: fix

#8078 Fix the visual test on the Label component
  js/label/Label.stories.svelte
Labels: v: patch

#8054 Fix Label component's value change detection to avoid infinite loop dispatching the change event
  .changeset/silly-drinks-glow.md
  js/label/Index.svelte
Labels: v: patch

#8080 Fix `gr.Interface.from_pipeline()` to allow audio uploads and to display classification labels correctly
  .changeset/flat-planets-love.md
  gradio/pipelines_utils.py
Labels: v: patch

#8093 [HF OAuth] Logout user if oauth token has expired
  .changeset/purple-radios-marry.md
  gradio/components/login_button.py
  gradio/processing_utils.py
  test/test_pipelines.py
Labels: v: patch

#8095 Update creating-a-realtime-dashboard-from-google-sheets.md
  guides/07_tabular-data-science-and-plots/creating-a-realtime-dashboard-from-google-sheets.md
Labels: v: patch

#8030 Store configs per session in the backend
  .changeset/twenty-corners-peel.md
  gradio/analytics.py
  gradio/blocks.py
  gradio/events.py
  gradio/helpers.py
  gradio/route_utils.py
  gradio/routes.py
  gradio/state_holder.py
  gradio/utils.py
  test/test_blocks.py
  test/test_buttons.py
  test/test_chat_interface.py
Labels: v: patch

#8051 Fix custom JS function caller to concat the outputs of a dep to the inputs as the arguments
  .changeset/funny-rice-say.md
  js/app/src/Blocks.svelte
Labels: v: patch

#8065 Hide the scroll bar in WaveformControls when it's not necessary
  .changeset/loud-ears-grab.md
  js/audio/shared/WaveformControls.svelte
Labels: v: patch

#8105 improve the documentation for `js` parameter in `Blocks`, `Interface`, `ChatInterface`
  .changeset/rotten-pears-pay.md
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/interface.py
Labels: v: patch

#8107 fix typo from #8105
  .changeset/cruel-heads-add.md
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/interface.py
Labels: v: patch

#8117 Add session hash to gr request
  .changeset/great-plants-deny.md
  .gitignore
  gradio/route_utils.py
  gradio/routes.py
Labels: v: patch

#8130 Add Analytics for custom components
  .changeset/mean-coins-push.md
  gradio/analytics.py
  gradio/cli/commands/components/build.py
  gradio/cli/commands/components/create.py
  gradio/cli/commands/components/dev.py
  gradio/cli/commands/components/docs.py
  gradio/cli/commands/components/publish.py
  gradio/cli/commands/components/show.py
  pnpm-lock.yaml
Labels: v: patch

#8115 Cache an error from app.submit() and show it on frontend
  .changeset/rich-bikes-crash.md
  js/app/src/Blocks.svelte
Labels: v: patch

#8081 Add tests for Lite custom element parser
  js/app/src/lite/custom-element/index.test.ts
Labels: v: patch

#8140 fix publish build
  .changeset/legal-bikes-switch.md
  .github/workflows/publish.yml
Labels: v: patch, t: fix

#8142 ensure @gradio/preview dist files are published
  .changeset/slick-buses-bake.md
  .github/workflows/publish.yml
Labels: v: patch, t: fix

#8143 chore: update versions
  .changeset/slick-buses-bake.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/preview/CHANGELOG.md
  js/preview/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8144 fix missing dependencies for `@gradio/preview`
  .changeset/silent-cases-brush.md
  js/preview/package.json
  js/preview/src/dev.ts
  js/preview/src/plugins.ts
  pnpm-lock.yaml
Labels: v: patch, t: fix

#8147 chore: update versions
  .changeset/silent-cases-brush.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/preview/CHANGELOG.md
  js/preview/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8170 Add ETag to `/custom_component` route to control browser caching
  .changeset/icy-otters-stand.md
  gradio/routes.py
Labels: t: fix

#8174 Remove hatch installation in js/app/package.json which is no longer needed
  .changeset/calm-goats-sit.md
  js/app/package.json
Labels: v: patch
