Repository gradio-app/gradio, pull requests merged in 2024-12, with the labels that each got.

#10080 Fix chatbot/chatinterface type mismatch
  .changeset/eight-games-decide.md
  gradio/chat_interface.py
  test/test_chat_interface.py
Labels: v: patch

#10089 9484-fix-windows-filepath-unit-tests
  test/components/test_image.py
  test/test_utils.py
Labels: windows-tests

#10130 Add docs for `additional_outputs` in `gr.ChatInterface`
  guides/05_chatbots/01_creating-a-chatbot-fast.md
Labels: v: patch

#10109 adds a `run_examples_on_click` parameter to `gr.ChatInterface` mirroring the the `run_on_click` parameter in `gr.Examples`
  .changeset/evil-hoops-attack.md
  demo/chatinterface_multimodal/run.ipynb
  demo/chatinterface_multimodal/run.py
  demo/test_chatinterface_multimodal_examples/cached_testcase.py
  demo/test_chatinterface_multimodal_examples/files/avatar.png
  demo/test_chatinterface_multimodal_examples/files/cantina.wav
  demo/test_chatinterface_multimodal_examples/run.ipynb
  demo/test_chatinterface_multimodal_examples/run.py
  gradio/chat_interface.py
  gradio/components/chatbot.py
  js/_website/generate_jsons/src/demos/__init__.py
  js/_website/generate_jsons/src/docs/__init__.py
  js/spa/test/test_chatinterface_multimodal_examples.spec.ts
Labels: v: minor

#10161 Fix chatbot `visible` prop not reacting to changes
  .changeset/new-chefs-build.md
  js/atoms/src/Block.svelte
Labels: v: patch, t: fix

#10166 Add Japanese translations for login UI
  .changeset/three-chefs-ask.md
  js/core/src/Login.svelte
  js/core/src/lang/en.json
  js/core/src/lang/ja.json
Labels: v: patch

#10188 Fix `multipart` ModuleNotFoundError by renaming import to `python_multipart`
  .changeset/wild-sheep-agree.md
  gradio/route_utils.py
  gradio/routes.py
Labels: v: patch

#10185 Clean up `gr.ChatInterface` and fix API type discrepancy
  .changeset/easy-buckets-judge.md
  gradio/chat_interface.py
  guides/05_chatbots/01_creating-a-chatbot-fast.md
  js/spa/test/test_chatinterface_streaming_echo.spec.ts
Labels: v: patch

#10193 JSON type fix in Client and and typing fix for `/chat` endpoint in `gr.ChatInterface`
  .changeset/warm-dragons-carry.md
  client/python/gradio_client/utils.py
  client/python/test/test_utils.py
  gradio/chat_interface.py
Labels: v: patch

#10196 Use the modern lower-case Python types in the API typing information
  .changeset/all-tables-appear.md
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
  client/python/test/test_utils.py
  test/test_api_info.py
Labels: v: patch

#10214 Some agent low-hanging issues
  .changeset/fifty-crabs-mix.md
  js/chatbot/Chatbot.stories.svelte
  js/chatbot/shared/Component.svelte
  js/chatbot/shared/Message.svelte
  js/chatbot/shared/MessageBox.svelte
  js/chatbot/shared/MessageContent.svelte
  js/spa/test/chatbot_with_tools.spec.ts
Labels: v: patch, t: fix

#10221 Update Guides related to deploying Gradio chatbots to Discord, Slack, and website widgets
  .changeset/seven-hands-kiss.md
  client/python/gradio_client/client.py
  guides/05_chatbots/01_creating-a-chatbot-fast.md
  guides/05_chatbots/06_creating-a-discord-bot-from-a-gradio-app.md
  guides/05_chatbots/07_creating-a-slack-bot-from-a-gradio-app.md
  guides/05_chatbots/08_creating-a-website-widget-from-a-gradio-chatbot.md
  guides/09_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
Labels: docs/website, v: patch

#9885 Update Transformers agent demo
  demo/agent_chatbot/requirements.txt
  demo/agent_chatbot/run.ipynb
  demo/agent_chatbot/run.py
  demo/agent_chatbot/utils.py
  guides/05_chatbots/03_agents-and-tool-usage.md
Labels: docs/website
