Repository gradio-app/gradio, pull requests merged in 2024-07, with the labels that each got.

#8683 Warn against Falsy credentials
  .changeset/chubby-spiders-love.md
  gradio/blocks.py
Labels: v: patch

#8686 Better spacing for codeblocks on docs
  .changeset/puny-bananas-prove.md
  js/_website/src/lib/assets/style.css
  js/_website/src/lib/templates/gradio/01_building-demos/02_chatinterface.svx
Labels: v: patch

#8624 Add search to website
  .changeset/wide-wasps-wait.md
  js/_website/generate_jsons/src/docs/__init__.py
  js/_website/package.json
  js/_website/src/lib/assets/style.css
  js/_website/src/lib/components/DocsNav.svelte
  js/_website/src/lib/components/Header.svelte
  js/_website/src/lib/components/JSDocsNav.svelte
  js/_website/src/lib/components/search/SearchIcon.svelte
  js/_website/src/lib/components/search/index.ts
  js/_website/src/lib/components/search/search-worker.ts
  js/_website/src/lib/components/search/search.svelte
  js/_website/src/lib/components/search/search.ts
  js/_website/src/routes/search-api/+server.ts
  pnpm-lock.yaml
Labels: v: patch

#8720 Documents auth in the guides, in the view API page, and also types the Blocks.config object
  .changeset/witty-pugs-beg.md
  client/js/src/types.ts
  globals.d.ts
  gradio/blocks.py
  gradio/data_classes.py
  gradio/external.py
  gradio/route_utils.py
  gradio/routes.py
  gradio/utils.py
  guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
  guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
  js/app/src/Blocks.svelte
  js/app/src/Index.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/CodeSnippet.svelte
  js/app/src/api_docs/RecordingSnippet.svelte
Labels: v: patch

#8744 Refactor `gr.ParamViewer` to use HTML `<details>` and other tweaks
  .changeset/heavy-beds-exist.md
  gradio/components/paramviewer.py
  js/paramviewer/Index.svelte
  js/paramviewer/ParamViewer.svelte
Labels: v: patch

#8750 Add guides for msg format and llm agents
  .changeset/gentle-wombats-thank.md
  .changeset/modern-comics-refuse.md
  .changeset/tangy-beds-guess.md
  .changeset/true-ears-knock.md
  .changeset/young-crabs-begin.md
  client/python/test/conftest.py
  demo/agent_chatbot/requirements.txt
  demo/agent_chatbot/run.ipynb
  demo/agent_chatbot/run.py
  demo/agent_chatbot/utils.py
  demo/blocks_xray/run.ipynb
  demo/blocks_xray/run.py
  demo/chatbot_core_components_simple/messages_testcase.py
  demo/chatbot_multimodal/messages_testcase.py
  demo/chatbot_streaming/testcase_messages.py
  demo/chatbot_with_tools/run.ipynb
  demo/chatbot_with_tools/run.py
  demo/chatinterface_streaming_echo/messages_testcase.py
  demo/test_chatinterface_streaming_echo/messages_testcase.py
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/components/chatbot.py
  gradio/data_classes.py
  gradio/interface.py
  guides/05_chatbots/03_messages-format.md
  guides/05_chatbots/04_agents-and-tool-usage.md
  guides/05_chatbots/05_creating-a-discord-bot-from-a-gradio-app.md
  js/_website/src/lib/templates/gradio/03_components/chatbot.svx
  js/app/src/Embed.svelte
  js/app/src/Index.svelte
  js/app/src/lite/LiteIndex.svelte
  js/app/src/lite/Playground.svelte
  js/app/src/lite/index.ts
  js/chatbot/Index.svelte
  js/plot/shared/plot_types/PlotlyPlot.svelte
  test/components/test_chatbot.py
  test/test_chat_interface.py
Labels: v: patch

#8767 chore: update versions
  .changeset/slimy-badgers-taste.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8774 Set the default format of gr.Plot as png for Wasm mode
  .changeset/three-eyes-know.md
  gradio/components/plot.py
Labels: v: patch

#8745 Allows updating the dataset of a `gr.Examples`
  .changeset/real-grapes-accept.md
  demo/image_mod/run.ipynb
  demo/image_mod/run.py
  gradio/blocks.py
  gradio/components/dataset.py
  gradio/helpers.py
  gradio/utils.py
  js/_website/src/lib/templates/gradio/04_helpers/11_examples.svx
  js/app/test/image_mod.spec.ts
  js/dataframe/Example.svelte
  test/components/test_dataset.py
  test/test_helpers.py
  test/test_utils.py
Labels: v: minor

#8618 Improve styling of parameter tables in the docs
  .changeset/ninety-ravens-care.md
  js/_website/package.json
  js/_website/src/lib/components/EventListeners.svelte
  js/_website/src/lib/components/FunctionDoc.svelte
  js/_website/src/lib/components/FunctionsSection.svelte
  js/_website/src/lib/components/ParamTable.svelte
  js/_website/src/lib/text.ts
  js/paramviewer/ParamViewer.svelte
  pnpm-lock.yaml
Labels: v: patch

#8809 Use constant-time comparison when checking user provided analytics key
  .changeset/ready-facts-worry.md
  gradio/routes.py
Labels: v: patch

#8821 Fix dependency loop with statustracker and markdown
  .changeset/swift-ghosts-spend.md
  js/statustracker/package.json
  js/statustracker/static/ToastContent.svelte
  pnpm-lock.yaml
Labels: v: patch

#8757 Document `FileData` class in docs
  .changeset/twenty-rice-bathe.md
  client/python/gradio_client/__init__.py
  client/python/gradio_client/documentation.py
  gradio/components/base.py
  gradio/data_classes.py
  js/_website/src/lib/templates/gradio/04_helpers/06_filedata.svx
Labels: v: patch

#8799 Remove Pydantic v2 patch from Lite
  .changeset/few-gifts-drive.md
  gradio/data_classes.py
  gradio/server_messages.py
  js/wasm/src/webworker/index.ts
Labels: v: patch

#8825 Fix param table rendering
  .changeset/huge-pears-like.md
  js/_website/src/routes/[[version]]/docs/gradio/[doc]/+page.svelte
Labels: v: patch

#8871 Add confirmation dialogue if leaving playground
  .changeset/cool-buckets-notice.md
  js/_website/src/lib/components/DemosLite.svelte
Labels: v: patch

#8926 fix typescript issue with custom components
  .changeset/weak-bottles-stick.md
  js/preview/src/plugins.ts
Labels: v: patch, t: fix

#8927 Fix `Could not resolve "virtual:component-loader"` in gradio/utils package
  .changeset/rude-women-fly.md
  js/utils/src/utils.ts
Labels: v: patch, t: fix
