Repository gradio-app/gradio, pull requests merged in 2024-01, with the labels that each got.

#6852 Use @gradio/image/shared/Image.svelte in the Gallery component for Wasm support
  .changeset/real-pumas-thank.md
  js/gallery/package.json
  js/gallery/shared/Gallery.svelte
  js/image/package.json
  js/image/shared/Image.svelte
  js/image/shared/index.ts
  pnpm-lock.yaml
Labels: gradio-lite

#6133 Lite: Support AnnotatedImage on Wasm
  .changeset/bumpy-cloths-dream.md
  js/annotatedimage/Index.svelte
  js/annotatedimage/package.json
  js/image/shared/Image.svelte
  js/video/shared/Video.svelte
  pnpm-lock.yaml
Labels: gradio-lite

#6931 Fix functional tests
  .changeset/empty-paths-write.md
  client/js/src/client.ts
  demo/cancel_events/run.ipynb
  demo/cancel_events/run.py
  gradio/analytics.py
  gradio/blocks.py
  gradio/components/file_explorer.py
  js/app/test/cancel_events.skip.spec.ts
  js/app/test/cancel_events.spec.ts
  js/app/test/image_component_events.spec.ts
  js/app/test/kitchen_sink.spec.ts
  js/app/test/upload_button_component_events.spec.ts
  js/fileexplorer/Index.svelte
  js/fileexplorer/shared/DirectoryExplorer.svelte
  js/image/Index.svelte
  js/upload/src/Upload.svelte
Labels: v: patch

#6956 Fixed (this this)
  .changeset/huge-roses-play.md
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/events.py
  gradio/interface.py
Labels: t: fix

#6963 fixed typo
  .changeset/tame-loops-clean.md
  gradio/flagging.py
Labels: v: patch

#6978 Lite: Fix and improve the file upload progress SSE
  gradio/route_utils.py
  gradio/routes.py
  js/app/src/lite/fetch.ts
  js/wasm/src/http.ts
  js/wasm/src/worker-proxy.ts
Labels: gradio-lite

#6965 Make <UploadProgress /> Wasm-compatible
  .changeset/fair-webs-type.md
  gradio/route_utils.py
  gradio/routes.py
  js/app/src/Index.svelte
  js/app/src/lite/fetch.ts
  js/app/src/lite/index.ts
  js/upload/src/UploadProgress.svelte
  js/wasm/src/http.ts
  js/wasm/src/worker-proxy.ts
  js/wasm/svelte/DownloadLink.svelte
  js/wasm/svelte/file-url.ts
Labels: gradio-lite

#6960 chore: update versions
  .changeset/brown-crews-tap.md
  .changeset/empty-bags-type.md
  .changeset/fair-webs-type.md
  .changeset/few-toes-clap.md
  .changeset/floppy-mugs-fall.md
  .changeset/fluffy-actors-tell.md
  .changeset/kind-flowers-punch.md
  .changeset/lazy-games-rush.md
  .changeset/swift-cooks-wish.md
  .changeset/tame-loops-clean.md
  .changeset/thirty-grapes-know.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  js/wasm/CHANGELOG.md
  js/wasm/package.json
  pnpm-lock.yaml
Labels: no-visual-update, windows-tests

#6998 ensure dist files are built before publishing
  .github/workflows/publish-npm.yml
Labels: v: patch

#6997 Design changes to Playground
  .changeset/upset-crabs-turn.md
  js/_website/src/lib/assets/img/anchor_gray.svg
  js/_website/src/lib/assets/img/share_gray.svg
  js/_website/src/lib/components/DemosLite.svelte
  js/_website/src/lib/components/Footer.svelte
  js/_website/src/lib/components/Header.svelte
  js/_website/src/routes/+layout.svelte
  js/_website/src/routes/playground/+page.svelte
  js/lite/index.html
Labels: v: patch

#7002 chore: update versions
  .changeset/cruel-nights-move.md
  .changeset/fast-doodles-carry.md
  .changeset/upset-crabs-turn.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update, windows-tests

#6933 Refactor examples so they accept data in the same format as is returned by function, rename `.as_example()` to `.process_example()`
  .changeset/large-olives-unite.md
  gradio/_simple_templates/simpledropdown.py
  gradio/components/audio.py
  gradio/components/base.py
  gradio/components/checkboxgroup.py
  gradio/components/dataframe.py
  gradio/components/dataset.py
  gradio/components/dropdown.py
  gradio/components/file.py
  gradio/components/image.py
  gradio/components/image_editor.py
  gradio/components/markdown.py
  gradio/components/model3d.py
  gradio/components/radio.py
  gradio/components/video.py
  gradio/processing_utils.py
  guides/05_custom-components/02_key-component-concepts.md
  guides/05_custom-components/04_backend.md
  guides/05_custom-components/06_frequently-asked-questions.md
  js/checkboxgroup/Example.svelte
  js/dropdown/Example.svelte
  js/image/Example.svelte
  js/imageeditor/Example.svelte
  js/radio/Example.svelte
  js/video/Example.svelte
  pnpm-lock.yaml
  test/test_components.py
  test/test_helpers.py
Labels: v: minor

#7048 Only run flaky tests if flaky-tests label is applied to PR
  .github/workflows/backend.yml
  .github/workflows/publish-npm.yml
Labels: flaky-tests

#7054 Add encoding to open/writing files on the deploy_discord function
  .changeset/modern-pugs-allow.md
  client/python/gradio_client/client.py
Labels: v: patch

#7075 fix lint
  .changeset/clear-papayas-hear.md
  client/python/gradio_client/client.py
  gradio/cli/commands/components/_docs_utils.py
Labels: v: patch

#6826 Add sample rate config option to `gr.Audio()`
  .changeset/weak-streets-check.md
  gradio/components/audio.py
  js/audio/Index.svelte
  js/audio/player/AudioPlayer.svelte
  js/audio/recorder/AudioRecorder.svelte
  js/audio/shared/audioBufferToWav.ts
  js/audio/shared/types.ts
  js/audio/shared/utils.ts
  test/test_components.py
Labels: v: minor

#7115 Programmatically determine max wheel version to push to spaces
  .changeset/famous-mammals-attend.md
  gradio/cli/commands/components/publish.py
Labels: custom-components

#7131 Miscellaneous doc fixes
  .changeset/clean-sheep-drive.md
  demo/interface_state/run.ipynb
  demo/interface_state/run.py
  gradio/components/audio.py
  gradio/components/state.py
  guides/02_building-interfaces/03_interface-state.md
  guides/03_building-with-blocks/01_blocks-and-event-listeners.md
Labels: v: patch

#7150 Lite: Add the `home_dir` to `sys.path`
  .changeset/smooth-bears-change.md
  js/wasm/src/webworker/py/script_runner.py
Labels: gradio-lite

#7130 Fix ParamViewer css
  .changeset/olive-hoops-hunt.md
  js/paramviewer/ParamViewer.svelte
Labels: v: patch

#7190 Add missing parameters and docstrings for `gr.TabbedInterface`
  .changeset/dirty-crabs-wear.md
  gradio/blocks.py
  gradio/external.py
  gradio/interface.py
Labels: v: minor

#7206 Upload tweak
  .changeset/eager-rivers-rescue.md
  .github/actions/install-frontend-deps/action.yml
  .github/workflows/backend.yml
  .github/workflows/build-pr.yml
  js/upload/src/UploadProgress.svelte
  package.json
Labels: v: patch

#7225 Fix test requirements to be compatible with python 3.11
  .changeset/strong-bugs-stick.md
  gradio/themes/base.py
  pyproject.toml
  test/requirements.in
  test/requirements.txt
Labels: v: patch

#7229 Fix hyphen-bug in gradio cc publish
  .changeset/spicy-rabbits-check.md
  gradio/cli/commands/components/publish.py
Labels: v: patch
