Repository gradio-app/gradio, pull requests merged in 2024-05, with the labels that each got.

#8106 Pass Error status in /dev/reload stream
  .changeset/slow-bats-sniff.md
  gradio/http_server.py
  gradio/routes.py
  gradio/utils.py
  js/app/src/Blocks.svelte
  js/app/src/Index.svelte
Labels: v: patch

#8182 Convert sse calls in client from async to sync
  .changeset/great-poets-visit.md
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
Labels: flaky-tests

#8194 run python reload only if python file changed
  .changeset/major-zoos-read.md
  gradio/utils.py
Labels: t: fix

#8180 Refactor analytics to not use api.gradio.app
  .changeset/gentle-berries-fetch.md
  gradio/analytics.py
  scripts/run_lite.sh
  test/test_analytics.py
Labels: v: patch, t: fix

#8205 Set the show_api flag on Lite
  .changeset/cruel-cars-think.md
  gradio/blocks.py
Labels: v: patch

#8052 Extend Interface.from_pipeline() to support Transformers.js.py pipelines on Lite
  .changeset/hungry-icons-serve.md
  gradio/interface.py
  gradio/pipelines.py
  gradio/pipelines_utils.py
  guides/08_gradio-clients-and-lite/03_fastapi-app-with-the-gradio-client.md
  guides/08_gradio-clients-and-lite/04_gradio-and-llm-agents.md
  guides/08_gradio-clients-and-lite/05_gradio-lite.md
  guides/08_gradio-clients-and-lite/06_gradio-lite-and-transformers-js.md
  js/lite/index2.html
Labels: gradio-lite

#8220 Convert all demos on docs to lite
  .changeset/mean-ads-hope.md
  js/_website/src/lib/components/Demos.svelte
  js/_website/src/routes/[[version]]/docs/gradio/[doc]/+page.svelte
Labels: v: patch

#8242 Allow Spaces with `.success()` to be `gr.load`-ed
  .changeset/social-tigers-lie.md
  gradio/blocks.py
  test/test_blocks.py
Labels: v: patch, t: fix

#8219 Apply clean_indent() to the file contents specified with <gradio-file> tags
  .changeset/major-buses-fold.md
  js/app/src/lite/custom-element/indent.ts
  js/app/src/lite/custom-element/index.test.ts
  js/app/src/lite/custom-element/index.ts
  js/app/src/lite/index.ts
Labels: v: patch

#8254 Fix custom component detection logic in analytics
  .changeset/common-worms-travel.md
  gradio/analytics.py
Labels: v: patch

#8236 Change upload icon for MultimodalTextbox
  .changeset/smooth-emus-cover.md
  js/app/test/chatbot_multimodal.spec.ts
  js/app/test/upload_file_limit_test.spec.ts
  js/icons/src/Paperclip.svelte
  js/icons/src/index.ts
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
Labels: v: patch

#8276 Fix bug where client could not connect to apps that had self signed certificates
  .changeset/cool-moments-dress.md
  client/python/gradio_client/client.py
Labels: v: patch, t: fix

#8264 Make exceptions in the Client more specific
  .changeset/blue-frogs-fetch.md
  client/python/gradio_client/client.py
  client/python/gradio_client/exceptions.py
  client/python/gradio_client/utils.py
  client/python/test/conftest.py
  client/python/test/test_client.py
  client/python/test/test_utils.py
Labels: v: patch

#8261 Fix bug where status tracker was the target of pointer events
  .changeset/tidy-groups-lose.md
  js/statustracker/static/index.svelte
Labels: t: fix

#8278 Embedded Lite example apps in the docs
  .changeset/khaki-toys-hammer.md
  guides/08_gradio-clients-and-lite/06_gradio-lite-and-transformers-js.md
  js/_website/src/routes/[[version]]/guides/[guide]/+page.server.ts
Labels: v: patch

#8260 Send ProcessCompleted message when job is cancelled
  .changeset/red-bottles-brake.md
  gradio/blocks.py
  gradio/events.py
  gradio/queueing.py
  gradio/routes.py
  gradio/utils.py
  test/test_blocks.py
Labels: v: patch, t: fix

#8263 Reduce the analytics that are collected in Gradio
  .changeset/shaggy-tables-fly.md
  client/python/test/test_client.py
  gradio/analytics.py
  gradio/blocks.py
  guides/03_additional-features/07_sharing-your-app.md
  js/app/src/Blocks.svelte
Labels: v: patch

#8285 use the correct query param to pass the jwt to the heartbeat event
  .changeset/dirty-apples-do.md
  client/js/src/client.ts
Labels: v: patch, t: fix

#8286 chore: update versions
  .changeset/dirty-apples-do.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_spaces-test/CHANGELOG.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8279 Link to troubleshooting guide in the custom component loading status
  .changeset/strong-cases-study.md
  guides/06_custom-components/06_frequently-asked-questions.md
  js/app/src/Index.svelte
  js/statustracker/static/index.svelte
Labels: v: patch, t: feat

#8296 always create a jwt when connecting to a space if a hf_token is present
  .changeset/ready-hotels-create.md
  client/js/src/client.ts
Labels: v: patch, t: fix

#8292 Ensure JSON component outputs handled properly in postprocess
  .changeset/gentle-socks-pay.md
  gradio/components/base.py
  gradio/components/json_component.py
  gradio/data_classes.py
  gradio/helpers.py
  gradio/processing_utils.py
  test/components/test_json.py
  test/test_helpers.py
  test/test_processing_utils.py
Labels: v: patch, t: fix

#8247 Fix api recorder
  .changeset/rotten-rabbits-reply.md
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  gradio/blocks.py
  gradio/component_meta.py
  gradio/events.py
  gradio/routes.py
  js/app/src/Blocks.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/RecordingSnippet.svelte
  js/app/src/api_docs/utils.ts
  js/app/test/test_chatinterface_streaming_echo.spec.ts
Labels: v: patch

#8319 Fix bad redirect breaking website build
  .changeset/red-streets-dress.md
  js/_website/src/routes/redirects.js
Labels: v: patch

#8320 chore: update versions
  .changeset/few-pillows-leave.md
  .changeset/red-streets-dress.md
  .changeset/rotten-rabbits-reply.md
  CHANGELOG.md
  client/python/CHANGELOG.md
  client/python/gradio_client/CHANGELOG.md
  client/python/gradio_client/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  requirements.txt
Labels: no-visual-update, windows-tests, flaky-tests

#8339 Fix Chatbot, Dataframe, Markdown custom components
  .changeset/tall-suits-train.md
  js/markdown/shared/MarkdownCode.svelte
  js/markdown/shared/utils.ts
Labels: t: fix

#8243 Add event listener support to render blocks
  .changeset/bitter-garlics-live.md
  client/js/src/helpers/api_info.ts
  client/js/src/helpers/data.ts
  client/js/src/helpers/init_helpers.ts
  client/js/src/test/data.test.ts
  client/js/src/test/test_data.ts
  client/js/src/types.ts
  client/js/src/utils/predict.ts
  client/js/src/utils/submit.ts
  client/python/gradio_client/client.py
  client/python/test/test_client.py
  demo/render_merge/run.ipynb
  demo/render_merge/run.py
  demo/state_change/run.ipynb
  demo/state_change/run.py
  gradio/analytics.py
  gradio/blocks.py
  gradio/component_meta.py
  gradio/components/clear_button.py
  gradio/components/duplicate_button.py
  gradio/components/login_button.py
  gradio/components/state.py
  gradio/context.py
  gradio/events.py
  gradio/external.py
  gradio/helpers.py
  gradio/queueing.py
  gradio/renderable.py
  gradio/route_utils.py
  gradio/routes.py
  gradio/state_holder.py
  gradio/utils.py
  js/app/src/Blocks.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/init.ts
  js/app/src/stores.ts
  js/app/src/types.ts
  js/app/test/render_merge.spec.ts
  test/components/test_plot.py
  test/test_blocks.py
  test/test_buttons.py
  test/test_chat_interface.py
Labels: v: patch

#8363 Add allow-credentials to preflight header
  .changeset/dark-streets-visit.md
  gradio/route_utils.py
Labels: v: patch

#8378 chore: update docs.py
  .changeset/thin-rings-drive.md
  gradio/cli/commands/components/docs.py
Labels: v: patch

#8386 Include instructions on starting from someone else's custom component repository
  .changeset/cute-ducks-fail.md
  gradio/cli/commands/components/build.py
  guides/06_custom-components/01_custom-components-in-five-minutes.md
  guides/06_custom-components/06_frequently-asked-questions.md
Labels: v: patch

#8398 Improve rendering
  .changeset/fine-pillows-open.md
  client/js/src/utils/submit.ts
  gradio/blocks.py
  gradio/events.py
  gradio/layouts/column.py
  gradio/layouts/row.py
  gradio/renderable.py
  gradio/routes.py
  gradio/utils.py
  js/app/src/init.ts
  js/app/src/types.ts
  js/column/Index.svelte
  js/column/package.json
  js/row/Index.svelte
  js/row/package.json
  js/statustracker/static/index.svelte
  pnpm-lock.yaml
Labels: v: patch

#8408 Connect heartbeat if state created in render. Also fix config cleanup bug #8407
  .changeset/easy-trains-obey.md
  client/js/src/client.ts
  client/js/src/utils/submit.ts
  gradio/blocks.py
  gradio/utils.py
Labels: v: patch, t: fix

#8420 chore: update versions
  .changeset/strong-years-battle.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_spaces-test/CHANGELOG.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
Labels: no-visual-update, windows-tests, flaky-tests
