Repository gradio-app/gradio, pull requests merged in 2024-02, with the labels that each got.

#7233 Make ci work
  .github/actions/changes/action.yml
  .github/actions/install-all-deps/action.yml
  .github/actions/install-frontend-deps/action.yml
  .github/workflows/backend.yml
  .github/workflows/build-pr.yml
  .github/workflows/check-demo-notebooks.yml
  .github/workflows/deploy+test-visual.yml
  .github/workflows/deploy-chromatic.yml
  .github/workflows/deploy-pr-to-spaces.yml
  .github/workflows/deploy-spaces.yml
  .github/workflows/deploy-website.yml
  .github/workflows/large-files.yml
  .github/workflows/publish.yml
  .github/workflows/report-notebook-status-pr.yml
  .github/workflows/test-functional.yml
  .github/workflows/test-hygiene.yml
  .github/workflows/test-python.yml
  .github/workflows/tests-js.yml
  .github/workflows/trigger.yml
  .github/workflows/ui.yml
  client/python/scripts/build_pypi.sh
  client/python/scripts/check_pypi.py
  client/python/scripts/format.sh
  client/python/scripts/lint.sh
  pyproject.toml
  scripts/check_pypi.py
  scripts/format_backend.sh
  style.md
Labels: windows-tests

#7236 Fix PIL imports
  .changeset/major-zoos-write.md
  gradio/components/annotated_image.py
  gradio/components/base.py
  gradio/components/gallery.py
  gradio/components/image.py
  gradio/components/image_editor.py
  gradio/image_utils.py
  gradio/templates.py
Labels: v: patch

#7274 chore: Change time format
  .changeset/mean-aliens-warn.md
  js/audio/player/AudioPlayer.svelte
  js/audio/recorder/AudioRecorder.svelte
  js/utils/src/utils.ts
  js/video/shared/Player.svelte
  js/video/shared/VideoControls.svelte
Labels: v: patch

#7292 Improvements to API Docs
  .changeset/shaggy-windows-glow.md
  js/app/src/Blocks.svelte
  js/app/src/api_docs/ApiDocs.svelte
Labels: v: patch

#7309 Add `gr.Image` interaction test + `gr.ImageEditor` interaction test improvement
  .changeset/pretty-ants-joke.md
  js/app/test/kitchen_sink.spec.ts
  js/image/shared/Webcam.svelte
  js/imageeditor/ImageEditor.stories.svelte
Labels: v: patch

#7332 Hotfix for: `stt_or_tts` demo
  .changeset/petite-years-call.md
  demo/stt_or_tts/run.ipynb
  demo/stt_or_tts/run.py
  gradio/external.py
Labels: v: patch

#6890 E2E tests for Lite
  .changeset/whole-swans-feel.md
  .config/playwright.config.js
  .github/workflows/test-functional.yml
  gradio/helpers.py
  js/app/package.json
  js/app/src/Index.svelte
  js/app/src/lite/dev/App.svelte
  js/app/src/lite/index.ts
  js/app/test/chatbot_multimodal.spec.ts
  js/app/vite.config.ts
  js/tootils/src/index.ts
Labels: gradio-lite

#7333 Stop using deprecated pydantic config class and filter gradio warnings from tests
  .changeset/itchy-garlics-hide.md
  gradio/data_classes.py
  pyproject.toml
Labels: v: patch

#7183 [WIP] Refactor file normalization to be in the backend and remove it from the frontend of each component
  .changeset/strong-chefs-study.md
  client/js/src/client.ts
  client/js/src/index.ts
  client/js/src/upload.ts
  client/python/gradio_client/utils.py
  gradio/blocks.py
  gradio/components/base.py
  gradio/components/login_button.py
  gradio/data_classes.py
  gradio/processing_utils.py
  gradio/route_utils.py
  gradio/routes.py
  guides/05_custom-components/05_frontend.md
  guides/05_custom-components/07_pdf-component-example.md
  js/annotatedimage/Index.svelte
  js/app/src/Index.svelte
  js/audio/Index.svelte
  js/chatbot/Chatbot.test.ts
  js/chatbot/Index.svelte
  js/file/Index.svelte
  js/gallery/Gallery.test.ts
  js/gallery/Index.svelte
  js/gallery/shared/Gallery.svelte
  js/image/Index.svelte
  js/image/shared/ImagePreview.svelte
  js/image/shared/ImageUploader.svelte
  js/imageeditor/Index.svelte
  js/imageeditor/shared/InteractiveImageEditor.svelte
  js/imageeditor/shared/tools/Sources.svelte
  js/model3D/Index.svelte
  js/simpleimage/Index.svelte
  js/simpleimage/shared/ImageUploader.svelte
  js/video/Index.svelte
  js/video/Video.test.ts
  test/test_components.py
Labels: v: minor

#7358 Fixing `gr.load()` part II
  .changeset/fresh-gifts-worry.md
  client/python/gradio_client/client.py
  gradio/processing_utils.py
Labels: v: minor

#7365 Update Pydantic patch for Lite that emulates PydanticV2 API using V1
  .changeset/two-pants-flow.md
  gradio/data_classes.py
Labels: gradio-lite

#7369 Remove the `@gradio/wasm` dependency from `@gradio/gallery` that is not used
  .changeset/social-loops-send.md
  js/gallery/package.json
  pnpm-lock.yaml
Labels: gradio-lite

#7377 Make set_documentation_group a no-op
  .changeset/rare-months-guess.md
  client/python/gradio_client/documentation.py
  gradio/cli/commands/components/_create_utils.py
  test/test_gradio_component_cli.py
Labels: v: patch

#7337 Improve File Explorer performance
  .changeset/chatty-rules-press.md
  demo/file_explorer/run.ipynb
  demo/file_explorer/run.py
  demo/file_explorer_component_events/dir3/dir3_bar.log
  demo/file_explorer_component_events/dir3/dir4/dir_4_bar.log
  demo/file_explorer_component_events/run.ipynb
  demo/file_explorer_component_events/run.py
  gradio/components/file_explorer.py
  js/app/test/file_explorer_component_events.spec.ts
  js/fileexplorer/Index.svelte
  js/fileexplorer/shared/Checkbox.svelte
  js/fileexplorer/shared/DirectoryExplorer.svelte
  js/fileexplorer/shared/FileTree.svelte
  js/fileexplorer/shared/types.ts
  js/fileexplorer/shared/utils.test.ts
  js/fileexplorer/shared/utils.ts
  scripts/copy_demos.py
  test/test_components.py
  test/test_utils.py
Labels: windows-tests

#7440 Prevent timing attacks to guess Gradio passwords
  .changeset/fine-pets-switch.md
  gradio/route_utils.py
  gradio/routes.py
  test/test_routes.py
Labels: v: patch

#7416 WIP: Optimize /file route
  .changeset/evil-lamps-refuse.md
  gradio/routes.py
Labels: v: patch

#7453 Make fix in #7444 (Block /file= filepaths that could expose credentials on Windows) more general
  .changeset/bumpy-wasps-march.md
  gradio/route_utils.py
  gradio/routes.py
  requirements.txt
  test/test_routes.py
Labels: v: patch

#7425 Fixes to the `.key_up()` method to make it usable for a dynamic dropdown autocomplete
  .changeset/witty-news-film.md
  gradio/blocks.py
  gradio/component_meta.py
  gradio/events.py
  js/dropdown/dropdown.test.ts
  js/dropdown/shared/Dropdown.svelte
Labels: v: patch

#7477 Enable Ruff S101
  .changeset/dirty-carrots-care.md
  client/python/gradio_client/client.py
  client/python/gradio_client/documentation.py
  client/python/gradio_client/serializing.py
  client/python/gradio_client/utils.py
  client/python/pyproject.toml
  client/python/test/requirements.txt
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/cli/commands/components/_create_utils.py
  gradio/cli/commands/components/publish.py
  gradio/component_meta.py
  gradio/components/audio.py
  gradio/components/base.py
  gradio/components/dataset.py
  gradio/components/dropdown.py
  gradio/components/video.py
  gradio/data_classes.py
  gradio/external.py
  gradio/external_utils.py
  gradio/flagging.py
  gradio/helpers.py
  gradio/interface.py
  gradio/ipython_ext.py
  gradio/processing_utils.py
  gradio/ranged_response.py
  gradio/route_utils.py
  gradio/routes.py
  gradio/tunneling.py
  gradio/utils.py
  pyproject.toml
  requirements.txt
  test/requirements.txt
  test/test_external.py
Labels: v: patch

#7465 Prevent components from working with non-uploaded files
  .changeset/moody-impalas-rule.md
  gradio/blocks.py
  gradio/processing_utils.py
  gradio/routes.py
  gradio/utils.py
Labels: v: patch

#7505 Fix `Gallery` preview overlay and backdrop
  .changeset/young-emus-find.md
  js/app/src/Blocks.svelte
  js/gallery/shared/Gallery.svelte
Labels: v: patch

#7503 Tighten CORS rules
  .changeset/olive-symbols-heal.md
  gradio/route_utils.py
  gradio/routes.py
  test/test_routes.py
Labels: v: patch

#7528 Refactors `get_fetchable_url_or_file()` to remove it from the frontend
  .changeset/thin-beers-worry.md
  client/js/src/index.ts
  client/js/src/upload.ts
  gradio/blocks.py
  gradio/components/base.py
  gradio/components/button.py
  gradio/components/chatbot.py
  gradio/components/dataset.py
  gradio/components/upload_button.py
  gradio/helpers.py
  gradio/processing_utils.py
  guides/05_custom-components/05_frontend.md
  guides/05_custom-components/07_pdf-component-example.md
  js/button/Button.stories.svelte
  js/button/Index.svelte
  js/button/shared/Button.svelte
  js/chatbot/Chatbot.stories.svelte
  js/chatbot/Index.svelte
  js/chatbot/shared/ChatBot.svelte
  js/dataframe/Example.svelte
  js/dataframe/README.md
  js/dataset/Index.svelte
  js/image/Example.svelte
  js/image/ImageExample.stories.svelte
  js/imageeditor/Example.svelte
  js/simpleimage/Example.svelte
  js/uploadbutton/Index.svelte
  js/uploadbutton/UploadButton.stories.svelte
  js/uploadbutton/UploadButton.test.ts
  js/uploadbutton/shared/UploadButton.svelte
  js/video/Example.svelte
  test/test_components.py
Labels: v: patch

#7544 Prevent paths beginning with `//` or `\\`
  .changeset/witty-walls-brake.md
  gradio/route_utils.py
  gradio/routes.py
  test/test_routes.py
Labels: v: patch
