Repository gradio-app/gradio, pull requests merged in 2024-10, with the labels that each got.

#9550 Fix most flaky Python tests in `5.0-dev` branch
  .changeset/busy-lizards-heal.md
  client/python/gradio_client/client.py
  client/python/test/test_client.py
  gradio/external.py
  gradio/external_utils.py
  gradio/themes/base.py
  requirements.txt
  test/requirements.txt
  test/test_external.py
Labels: flaky-tests

#9623 Fix Chatbot Examples Error
  .changeset/moody-squids-kiss.md
  demo/test_chatinterface_examples/multimodal_messages_examples_testcase.py
  demo/test_chatinterface_examples/multimodal_tuples_examples_testcase.py
  demo/test_chatinterface_examples/run.ipynb
  demo/test_chatinterface_examples/run.py
  demo/test_chatinterface_examples/tuples_examples_testcase.py
  gradio/chat_interface.py
  js/chatbot/shared/ButtonPanel.svelte
  js/chatbot/shared/ChatBot.svelte
  js/spa/test/test_chatinterface_examples.spec.ts
Labels: v: patch

#9630 Fix duplicate attribute error
  .changeset/rich-jeans-march.md
  js/app/src/app.html
  js/app/src/routes/[...catchall]/+page.svelte
  js/chatbot/shared/ButtonPanel.svelte
  js/chatbot/shared/ChatBot.svelte
  js/lite/src/Playground.svelte
Labels: v: patch, t: fix

#9632 bump to node 20
  .changeset/clear-walls-unite.md
  gradio/blocks.py
  gradio/node_server.py
  gradio/routes.py
  gradio/utils.py
  guides/08_custom-components/01_custom-components-in-five-minutes.md
  guides/08_custom-components/07_pdf-component-example.md
Labels: v: patch, t: fix

#9656 Fix streaming Audio/Video Output
  .changeset/silly-hairs-burn.md
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/components/audio.py
  gradio/components/video.py
  gradio/routes.py
Labels: v: patch

#9716 Restore light/dark custom setting
  .changeset/calm-emus-post.md
  gradio/themes/base.py
Labels: v: patch, t: fix

#9719 Fix Lite dependencies
  .changeset/calm-roses-suffer.md
  js/wasm/src/webworker/index.ts
  requirements.txt
Labels: v: patch

#9731 fix css syntax error
  .changeset/stale-jobs-reply.md
  gradio/themes/base.py
Labels: v: patch, t: fix

#9711 Custom component fixes
  .changeset/hot-dancers-drop.md
  js/atoms/package.json
  js/build/out/index.js
  js/build/src/index.ts
  js/markdown/package.json
  js/markdown/shared/MarkdownCode.svelte
  js/sanitize/browser.ts
  js/sanitize/index.d.ts
  js/sanitize/package.json
  js/sanitize/server.ts
  pnpm-lock.yaml
Labels: v: patch, t: fix

#9713 Fix functional tests pt 2
  js/spa/test/audio_component_events.spec.ts
  js/spa/test/blocks_chained_events.spec.ts
  js/spa/test/file_component_events.spec.ts
  js/spa/test/image_component_events.spec.ts
  js/spa/test/image_editor_events.spec.ts
  js/spa/test/test_chatinterface.reload.spec.ts
  js/spa/test/upload_file_limit_test.spec.ts
  js/spa/test/video_component_events.spec.ts
Labels: v: patch, t: fix

#9746 fix `@gradio/sanitize` exports
  .changeset/few-weeks-change.md
  js/sanitize/package.json
Labels: v: patch, t: feat

#9738 Export `Tabs` type from `@gradio/tabs` and fix the Playground to be compatible with the new Tabs API
  .changeset/small-chicken-retire.md
  js/_website/src/lib/components/DemosLite.svelte
  js/tabs/Index.svelte
  js/tabs/shared/Tabs.svelte
Labels: v: patch, t: fix

#9700 Fix API info bug
  .changeset/olive-lights-hide.md
  gradio/routes.py
Labels: v: patch, t: fix

#9707 Add a port timeout detection feature for gradio/preview.
  .changeset/honest-forks-pay.md
  js/preview/src/index.ts
Labels: v: patch, t: fix

#9765 Fixes SVG Icons
  .changeset/tangy-eyes-begin.md
  gradio/processing_utils.py
  gradio/utils.py
  guides/04_additional-features/08_file-access.md
Labels: v: patch, t: fix

#9783 Exclude python-multipart 0.0.13
  .changeset/warm-roses-begin.md
  requirements.txt
Labels: v: patch

#9814 support gradio apps on spaces served on subpaths
  .changeset/odd-wolves-taste.md
  client/js/src/helpers/api_info.ts
  client/js/src/helpers/init_helpers.ts
  client/js/src/test/api_info.test.ts
Labels: v: patch, t: fix

#9815 use different env var for node port range
  .changeset/tame-grapes-look.md
  gradio/node_server.py
  guides/04_additional-features/09_environment-variables.md
Labels: v: patch, t: fix

#9827 Fix Loading SSR'd apps via gr.load
  .changeset/long-wolves-serve.md
  gradio/external.py
Labels: v: patch, t: fix

#9826 Make sure the Tool accordion is closed if it is not the last message
  .changeset/slow-baboons-report.md
  js/chatbot/shared/Message.svelte
Labels: v: patch, t: fix
