Repository gradio-app/gradio, pull requests merged in 2024-03, with the labels that each got.

#7345 fix-tests
  .changeset/tired-pants-relax.md
  .config/playwright.config.js
  .github/actions/install-all-deps/action.yml
  .github/actions/install-frontend-deps/action.yml
  .github/workflows/test-functional.yml
  gradio/components/gallery.py
  js/app/src/lite/custom-element/index.ts
  js/app/src/lite/dev/App.svelte
  js/app/src/lite/index.ts
  js/app/vite.config.ts
  js/lite/for_e2e.html
  js/tootils/src/index.ts
  js/wasm/src/webworker/index.ts
  js/wasm/svelte/DownloadLink.svelte
  js/wasm/svelte/file-url.ts
Labels: v: patch

#7447 Add delete_cache parameter to gr.Blocks to delete files created by app on shutdown
  .changeset/public-hoops-drum.md
  gradio/blocks.py
  gradio/chat_interface.py
  gradio/components/base.py
  gradio/components/dataset.py
  gradio/interface.py
  gradio/route_utils.py
  gradio/routes.py
  guides/01_getting-started/03_sharing-your-app.md
  test/conftest.py
  test/test_blocks.py
  test/test_routes.py
Labels: v: minor

#7614 Fix the `root_url` logic for streaming files
  .changeset/fluffy-mice-joke.md
  .gitignore
  demo/fake_diffusion_with_gif/image.gif
  demo/fake_diffusion_with_gif/run.ipynb
  gradio/blocks.py
  gradio/processing_utils.py
  gradio/queueing.py
  gradio/route_utils.py
  gradio/routes.py
  test/test_blocks.py
  test/test_utils.py
Labels: v: patch

#7617 fix flaky python tests
  client/python/test/test_utils.py
  test/test_external.py
Labels: v: patch, flaky-tests

#7625 image upload fix
  .changeset/common-months-guess.md
  js/upload/src/Upload.svelte
Labels: v: patch

#7626 chore: update versions
  .changeset/common-months-guess.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  pnpm-lock.yaml
Labels: no-visual-update, windows-tests, flaky-tests

#7571 Fix `CrossOriginWorkerMaker` to cache the blob URL
  .changeset/tidy-fans-scream.md
  js/wasm/src/cross-origin-worker.ts
Labels: gradio-lite

#7575 Files should now be supplied as `file(...)` in the Client, and some fixes to `gr.load()` as well
  .changeset/hungry-donuts-nail.md
  client/js/src/client.ts
  client/js/src/types.ts
  client/js/src/upload.ts
  client/python/gradio_client/__init__.py
  client/python/gradio_client/client.py
  client/python/gradio_client/compatibility.py
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
  gradio/_simple_templates/simpleimage.py
  gradio/blocks.py
  gradio/components/annotated_image.py
  gradio/components/audio.py
  gradio/components/base.py
  gradio/components/dataset.py
  gradio/components/download_button.py
  gradio/components/file.py
  gradio/components/gallery.py
  gradio/components/image.py
  gradio/components/image_editor.py
  gradio/components/model3d.py
  gradio/components/upload_button.py
  gradio/components/video.py
  gradio/data_classes.py
  gradio/external.py
  gradio/processing_utils.py
  guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
  js/app/src/api_docs/CodeSnippets.svelte
  js/app/src/api_docs/utils.ts
  test/test_components.py
  test/test_external.py
  test/test_processing_utils.py
Labels: v: minor, flaky-tests

#7650 downgrade contourpy
  .changeset/thirty-falcons-leave.md
  gradio/cli/commands/cli_env_info.py
  gradio/cli/commands/components/build.py
  gradio/cli/commands/components/create.py
  gradio/cli/commands/components/dev.py
  gradio/cli/commands/components/install_component.py
  gradio/cli/commands/components/publish.py
  gradio/cli/commands/components/show.py
  test/requirements.txt
  test/test_routes.py
Labels: windows-tests

#7700 Run Linux CI on Python 3.8
  .github/actions/install-all-deps/action.yml
Labels: windows-tests

#7704 Fix flagged files and ensure that flagging_mode="auto" saves output components as well
  .changeset/social-lies-nail.md
  gradio/components/base.py
  gradio/components/code.py
  gradio/components/json_component.py
  gradio/flagging.py
  gradio/helpers.py
  gradio/interface.py
  gradio/utils.py
  test/test_flagging.py
Labels: v: minor

#7718 Add support for python client connecting to gradio apps running with self-signed SSL certificates
  .changeset/kind-eyes-shake.md
  client/python/gradio_client/client.py
  client/python/gradio_client/compatibility.py
  client/python/gradio_client/utils.py
  client/python/test/test_client.py
  client/python/test/test_utils.py
Labels: flaky-tests

#7712 More fixes for `gr.load()` as well as a tweaking the `__str__` and `__repr__` methods of components
  .changeset/famous-years-itch.md
  gradio/blocks.py
  gradio/components/base.py
  test/test_blocks.py
  test/test_components.py
Labels: v: patch

#7572 Detailed error message for wasm_utils.get_registered_app()
  .changeset/major-results-stick.md
  gradio/wasm_utils.py
Labels: gradio-lite

#7691 Closing stream from the backend
  .changeset/curly-parents-dream.md
  .changeset/thick-penguins-act.md
  client/js/src/client.ts
  client/python/gradio_client/client.py
  client/python/gradio_client/utils.py
  gradio/blocks.py
  gradio/routes.py
  gradio/server_messages.py
  js/app/src/Blocks.svelte
Labels: v: patch

#7743 Migrate to Storybook 8
  .changeset/angry-files-pick.md
  js/dropdown/dropdown.test.ts
  js/image/Image.stories.svelte
  js/imageeditor/ImageEditor.stories.svelte
  js/radio/Radio.test.ts
  js/radio/shared/Radio.svelte
  js/storybook/main.ts
  js/storybook/preview.ts
  js/video/Video.stories.svelte
  package.json
  pnpm-lock.yaml
Labels: v: patch

#7747 fix dataframe stories
  js/dataframe/Dataframe.stories.svelte
Labels: v: patch

#7762 Trigger input event for Radio even when radio is output component
  .changeset/mighty-bags-begin.md
  js/radio/Index.svelte
Labels: v: patch

#7732 Adds support for kwargs and default arguments in the python client, and improves how parameter information is displayed in the "view API" page
  .changeset/tiny-bars-greet.md
  client/python/gradio_client/client.py
  client/python/gradio_client/data_classes.py
  client/python/gradio_client/utils.py
  client/python/test/conftest.py
  client/python/test/test_client.py
  client/python/test/test_utils.py
  gradio/blocks.py
  gradio/utils.py
  guides/01_getting-started/03_sharing-your-app.md
  guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/CodeSnippet.svelte
  js/app/src/api_docs/InstallSnippet.svelte
  js/app/src/api_docs/ParametersSnippet.svelte
  js/app/src/api_docs/ResponseObject.svelte
  js/app/src/api_docs/ResponseSnippet.svelte
  js/app/src/api_docs/utils.ts
  js/atoms/src/Block.svelte
  test/test_external.py
  test/test_utils.py
Labels: flaky-tests

#7787 Fix root url resolution from `x_forwarded_host` headers
  .changeset/ripe-coins-poke.md
  gradio/route_utils.py
  test/test_routes.py
Labels: v: patch

#7794 Adds trigger_mode to gr.on. Use it to set trigger_model="always_last" for live interfaces.
  .changeset/two-suns-trade.md
  gradio/events.py
  gradio/interface.py
  test/test_interfaces.py
Labels: v: patch

#7800 Small fix to client.view_api() in the case of default file values
  .changeset/clever-masks-melt.md
  client/python/gradio_client/client.py
Labels: v: patch

#7789 Remove the aiohttp mock from the Wasm worker as it's removed in https://github.com/gradio-app/gradio/pull/5244
  .changeset/whole-jokes-drum.md
  js/wasm/src/webworker/index.ts
Labels: v: patch

#7823 Exclude `typer` from the requirements list for Wasm env and fix `gradio.cli` not to be imported
  .changeset/silly-spies-cross.md
  gradio/__init__.py
  gradio/blocks.py
  requirements.txt
Labels: v: patch, gradio-lite

#7818 Stop importing gradio.ipython_ext in Wasm mode
  .changeset/neat-numbers-matter.md
  gradio/__init__.py
Labels: v: patch

#7801 Refactor CORS Middleware to be much faster
  .changeset/stale-grapes-roll.md
  gradio/route_utils.py
Labels: v: patch

#7830 Add guide on Client state and and fix default values of components
  .changeset/puny-planets-cover.md
  client/python/test/test_client.py
  gradio/_simple_templates/simpletextbox.py
  gradio/components/html.py
  gradio/components/markdown.py
  gradio/components/textbox.py
  gradio/templates.py
  guides/08_gradio-clients-and-lite/01_getting-started-with-the-python-client.md
  test/test_components.py
Labels: v: patch

#7840 Fix gradio/components/dataframe.py not to import `pandas.io`
  .changeset/solid-cars-spend.md
  gradio/components/dataframe.py
Labels: v: patch

#7835 Stop running iterators when js client disconnects
  .changeset/eighty-ends-invent.md
  .gitignore
  demo/cancel_events/run.ipynb
  demo/cancel_events/run.py
  gradio/routes.py
  js/app/test/cancel_events.spec.ts
Labels: v: patch

#7851 Lazy-import pandas
  .changeset/sixty-buses-know.md
  gradio/components/bar_plot.py
  gradio/components/dataframe.py
  gradio/components/line_plot.py
  gradio/components/scatter_plot.py
Labels: v: patch

#7810 Benchmark fix test
  .changeset/young-ducks-scream.md
  gradio/queueing.py
  gradio/routes.py
Labels: v: patch

#7862 Trigger click event from `gr.DownloadButton` even when no file is present
  .changeset/famous-wings-shout.md
  js/downloadbutton/shared/DownloadButton.svelte
Labels: v: patch

#7869 Make buttons in `gr.ChatInterface` more mobile-friendly
  .changeset/shaggy-symbols-tie.md
  gradio/chat_interface.py
Labels: v: patch

#7875 Fix how files are processed in `gr.ChatInterface`
  .changeset/sixty-paths-push.md
  gradio/chat_interface.py
  guides/04_chatbots/01_creating-a-chatbot-fast.md
  test/test_processing_utils.py
Labels: v: patch

#7888 Cache view_api info in server and python client
  .changeset/legal-teams-camp.md
  client/python/gradio_client/client.py
  client/python/test/conftest.py
  client/python/test/test_client.py
  gradio/routes.py
Labels: v: patch

#7872 Paste Images into MultimodalTextbox
  .changeset/sixty-paths-push.md
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
Labels: v: patch

#7892 Suppress printing "Running on local URL:" when quiet is set
  .changeset/green-brooms-work.md
  gradio/blocks.py
Labels: v: patch

#7893 Make internal event handlers of gr.Interface and gr.ChatInterface async
  .changeset/strong-hornets-push.md
  gradio/chat_interface.py
  gradio/interface.py
  gradio/utils.py
Labels: v: patch
