Repository gradio-app/gradio, pull requests merged in 2024-06, with the labels that each got.

#8433 chore: update versions
  .changeset/three-walls-sell.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8440 Add support for `numpy~=2.0`
  .changeset/ripe-ears-tease.md
  gradio/processing_utils.py
  requirements.txt
Labels: v: patch, t: fix

#8377 Click to preview images in chatbot
  .changeset/dirty-wings-double.md
  js/chatbot/shared/ChatBot.svelte
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
Labels: v: patch

#8429 Fix type hints for render and on
  .changeset/breezy-bottles-hide.md
  gradio/events.py
  gradio/renderable.py
Labels: v: patch

#8455 Fix multimodal textbox placeholder
  .changeset/quick-waves-train.md
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
Labels: v: patch

#8456 Add website banner for clients launch
  .changeset/short-pets-brake.md
  js/_website/src/lib/components/Header.svelte
Labels: v: patch

#8443 chore: update versions
  .changeset/breezy-bottles-hide.md
  .changeset/dirty-wings-double.md
  .changeset/fair-items-sort.md
  .changeset/nice-plums-bet.md
  .changeset/quick-waves-train.md
  .changeset/ripe-ears-tease.md
  .changeset/short-pets-brake.md
  .changeset/young-lamps-press.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8445 Add cURL to view API Page and add a dedicated Guide
  .changeset/ripe-tires-nail.md
  .config/.prettierignore
  gradio/routes.py
  guides/08_gradio-clients-and-lite/03_querying-gradio-apps-with-curl.md
  guides/08_gradio-clients-and-lite/07_fastapi-app-with-the-gradio-client.md
  js/app/src/api_docs/ApiBanner.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/CodeSnippet.svelte
  js/app/src/api_docs/InstallSnippet.svelte
  js/app/src/api_docs/ParametersSnippet.svelte
  js/app/src/api_docs/RecordingSnippet.svelte
  js/app/src/api_docs/ResponseSnippet.svelte
  js/app/src/api_docs/img/bash.svg
  js/app/src/api_docs/utils.ts
Labels: v: patch

#8370 Refactor Cancelling Logic To Use /cancel
  .changeset/deep-weeks-show.md
  client/js/src/helpers/api_info.ts
  client/js/src/test/test_data.ts
  client/js/src/types.ts
  client/js/src/utils/submit.ts
  gradio/blocks.py
  gradio/events.py
  gradio/routes.py
  gradio/utils.py
  js/app/src/Blocks.svelte
  js/app/src/types.ts
  test/test_blocks.py
Labels: v: patch

#8460 Support Bash in Api Recorder
  .changeset/empty-moons-stick.md
  .config/.prettierignore
  guides/08_gradio-clients-and-lite/03_querying-gradio-apps-with-curl.md
  js/app/src/api_docs/ApiBanner.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/CodeSnippet.svelte
  js/app/src/api_docs/RecordingSnippet.svelte
Labels: v: patch

#8471 Tweak meta titles and descriptions for clients
  .changeset/early-files-allow.md
  js/_website/src/lib/templates/python-client/gradio_client/01_introduction.svx
  js/_website/src/routes/[[version]]/docs/js-client/+page.svelte
  js/_website/src/routes/[[version]]/docs/python-client/[doc]/+page.svelte
Labels: v: patch

#8477 Fix js client bundle
  .changeset/clever-windows-swim.md
  client/js/vite.config.js
Labels: v: patch, t: fix

#8473 Improve design of api recorder
  .changeset/pink-bananas-sleep.md
  js/app/src/api_docs/ApiBanner.svelte
  js/app/src/api_docs/ApiDocs.svelte
  js/app/src/api_docs/ApiRecorder.svelte
  js/app/test/test_chatinterface_streaming_echo.spec.ts
Labels: v: patch

#8483 documentation for @gradio/client
  .changeset/plain-mice-help.md
  client/js/README.md
  guides/08_gradio-clients-and-lite/02_getting-started-with-the-js-client.md
Labels: v: patch

#8482 chore: update versions
  .changeset/crazy-turtles-sing.md
  .changeset/plain-mice-help.md
  .changeset/quiet-colts-burn.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  client/python/CHANGELOG.md
  client/python/gradio_client/CHANGELOG.md
  client/python/gradio_client/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_spaces-test/CHANGELOG.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
  requirements.txt
Labels: no-visual-update, windows-tests, flaky-tests

#8486 chore: update versions
  .changeset/common-paws-grab.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8487 Add Client Release Notes to Docs
  .changeset/strong-pants-create.md
  js/_website/src/lib/assets/style.css
  js/_website/src/lib/templates/python-client/gradio_client/02_version-1-release.svx
Labels: v: patch

#8491 Remove broken guide redirect
  .changeset/long-tables-guess.md
  js/_website/src/routes/redirects.js
  js/upload/package.json
  pnpm-lock.yaml
Labels: v: patch

#8499 Cache break themes on change
  .changeset/tall-keys-report.md
  client/js/src/types.ts
  globals.d.ts
  gradio/blocks.py
  js/app/src/Index.svelte
Labels: v: patch

#8497 chore: update versions
  .changeset/long-tables-guess.md
  .changeset/pretty-clowns-fall.md
  .changeset/strong-pants-create.md
  .changeset/tall-keys-report.md
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_spaces-test/CHANGELOG.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8516 Add helper classes to docs
  .changeset/three-pears-shout.md
  client/python/gradio_client/documentation.py
  gradio/components/audio.py
  gradio/components/image_editor.py
  js/_website/generate_jsons/src/docs/__init__.py
  js/_website/src/lib/assets/style.css
  js/_website/src/lib/components/HelpersSection.svelte
  js/_website/src/lib/templates/gradio/03_components/01_introduction.svx
  js/_website/src/lib/templates/gradio/03_components/audio.svx
  js/_website/src/lib/templates/gradio/03_components/imageeditor.svx
  js/_website/src/lib/text.ts
Labels: v: patch

#8488 Minor changes to monitoring
  .changeset/ripe-aliens-pick.md
  gradio/monitoring_dashboard.py
  gradio/routes.py
Labels: v: patch

#8537 Many small fixes to website and docs
  .changeset/true-places-post.md
  gradio/helpers.py
  js/_website/generate_jsons/generate.py
  js/_website/generate_jsons/src/docs/__init__.py
  js/_website/src/lib/components/DocsNav.svelte
  js/_website/src/lib/components/EventListeners.svelte
  js/_website/src/lib/components/FunctionDoc.svelte
  js/_website/src/lib/components/Header.svelte
  js/_website/src/lib/components/ParamTable.svelte
  js/_website/src/routes/[[version]]/docs/+layout.server.ts
  js/_website/src/routes/[[version]]/docs/gradio/[doc]/+page.svelte
  js/_website/src/routes/[[version]]/docs/js-client/+page.server.ts
  js/_website/src/routes/[[version]]/docs/js-client/+page.svelte
  js/_website/src/routes/[[version]]/docs/python-client/[doc]/+page.svelte
  scripts/upload_website_demos.py
Labels: v: patch, t: fix

#8543 Ability to disable orange progress animation for generators
  .changeset/nasty-actors-kick.md
  gradio/chat_interface.py
  gradio/interface.py
  js/statustracker/static/index.svelte
Labels: v: patch, t: fix

#8548 Fix reload mode by implementing `close` on the client
  .changeset/red-rice-build.md
  client/js/src/client.ts
  js/app/test/test_chatinterface.reload.spec.ts
Labels: v: patch, t: fix

#8559 fix website build
  .changeset/tangy-bats-laugh.md
  js/_website/vite.config.ts
Labels: v: patch, t: fix

#8565 Remove duplicated code in `routes.py`
  .changeset/slick-dancers-lie.md
  gradio/routes.py
Labels: v: patch

#8571 First time loading performance optimization
  .changeset/stale-crabs-return.md
  client/js/src/globals.d.ts
  client/js/src/utils/view_api.ts
  globals.d.ts
  gradio/routes.py
  js/app/build_plugins.ts
  js/app/index.html
Labels: v: patch

#8580 Improved plot rendering
  .changeset/twenty-jokes-argue.md
  demo/native_plots/bar_plot_demo.py
  demo/native_plots/line_plot_demo.py
  demo/native_plots/scatter_plot_demo.py
  gradio/components/bar_plot.py
  gradio/components/line_plot.py
  gradio/components/scatter_plot.py
  js/plot/Plot.stories.svelte
  js/plot/package.json
  js/plot/shared/Plot.svelte
  js/plot/shared/plot_types/AltairPlot.svelte
  js/plot/shared/plot_types/BokehPlot.svelte
  js/plot/shared/plot_types/MatplotlibPlot.svelte
  js/plot/shared/plot_types/PlotlyPlot.svelte
  js/plot/shared/plot_types/altair_utils.ts
  js/plot/shared/utils.ts
  js/plot/testplot.js
  pnpm-lock.yaml
  test/components/test_bar_plot.py
  test/components/test_line_plot.py
  test/components/test_scatter_plot.py
Labels: v: patch

#8555 support html in chatbot
  .changeset/pretty-worlds-trade.md
  demo/chatbot_core_components/run.ipynb
  demo/chatbot_core_components/run.py
  gradio/components/chatbot.py
  js/chatbot/shared/ChatBot.svelte
  js/html/package.json
Labels: v: minor, t: feat

#8593 Adding more docs for using components in chatbot
  .changeset/evil-heads-take.md
  demo/chatbot_core_components_simple/files/audio.wav
  demo/chatbot_core_components_simple/files/avatar.png
  demo/chatbot_core_components_simple/files/sample.txt
  demo/chatbot_core_components_simple/files/world.mp4
  demo/chatbot_core_components_simple/run.ipynb
  demo/chatbot_core_components_simple/run.py
  gradio/components/chatbot.py
  guides/05_chatbots/01_creating-a-chatbot-fast.md
  js/_website/src/lib/templates/gradio/03_components/chatbot.svx
Labels: v: patch

#8609 Changed gradio version check from print statement to warning
  .changeset/fifty-books-fly.md
  gradio/analytics.py
Labels: v: patch, t: fix

#8606 Fix plotly version
  scripts/copy_demos.py
Labels: v: patch, t: fix

#8603 Fix resizer on altair
  .changeset/few-camels-swim.md
  js/plot/shared/plot_types/AltairPlot.svelte
Labels: v: patch

#8613 chore: update versions
  .changeset/smart-rooms-win.md
  CHANGELOG.md
  gradio/CHANGELOG.md
  gradio/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
Labels: no-visual-update, windows-tests, flaky-tests

#8604 Add docs for `.on()`, `.then()`, and `.success()`, as well as the subclasses of `gr.EventData`
  .changeset/tiny-bats-cut.md
  gradio/events.py
  js/_website/src/lib/templates/gradio/04_helpers/01_eventdata.svx
  js/_website/src/lib/templates/gradio/04_helpers/02_deletedfiledata.svx
  js/_website/src/lib/templates/gradio/04_helpers/03_keyupdata.svx
  js/_website/src/lib/templates/gradio/04_helpers/04_likedata.svx
  js/_website/src/lib/templates/gradio/04_helpers/05_selectdata.svx
  js/_website/src/lib/templates/gradio/04_helpers/10_progress.svx
  js/_website/src/lib/templates/gradio/04_helpers/11_examples.svx
  js/_website/src/lib/templates/gradio/04_helpers/12_dependency.svx
  js/_website/src/lib/templates/gradio/04_helpers/on.svx
Labels: v: patch

#8619 Adds section on authentication in cURL
  guides/08_gradio-clients-and-lite/03_querying-gradio-apps-with-curl.md
Labels: v: patch

#8632 remove `chatbot_multimodal` demo from `gr.Chatbot` documentation page
  .changeset/blue-moons-learn.md
  gradio/components/chatbot.py
Labels: v: patch

#8637 Multimodal textbox buttons alignment
  .changeset/lovely-phones-punch.md
  js/multimodaltextbox/shared/MultimodalTextbox.svelte
Labels: v: patch, t: fix

#8622 chore: update versions
  .changeset/blue-moons-learn.md
  .changeset/curvy-clowns-design.md
  .changeset/fancy-mugs-guess.md
  .changeset/fresh-years-feel.md
  .changeset/great-insects-see.md
  .changeset/little-falcons-chew.md
  .changeset/lovely-phones-punch.md
  .changeset/tiny-bats-cut.md
  .changeset/wild-cases-obey.md
  =23.2
  CHANGELOG.md
  client/js/CHANGELOG.md
  client/js/package.json
  gradio/CHANGELOG.md
  gradio/package.json
  js/_spaces-test/CHANGELOG.md
  js/_website/CHANGELOG.md
  js/_website/package.json
  js/annotatedimage/CHANGELOG.md
  js/annotatedimage/package.json
  js/app/CHANGELOG.md
  js/app/package.json
  js/audio/CHANGELOG.md
  js/audio/package.json
  js/button/CHANGELOG.md
  js/button/package.json
  js/chatbot/CHANGELOG.md
  js/chatbot/package.json
  js/code/CHANGELOG.md
  js/code/package.json
  js/dataframe/CHANGELOG.md
  js/dataframe/package.json
  js/dataset/CHANGELOG.md
  js/dataset/package.json
  js/downloadbutton/CHANGELOG.md
  js/downloadbutton/package.json
  js/file/CHANGELOG.md
  js/file/package.json
  js/fileexplorer/CHANGELOG.md
  js/fileexplorer/package.json
  js/gallery/CHANGELOG.md
  js/gallery/package.json
  js/image/CHANGELOG.md
  js/image/package.json
  js/imageeditor/CHANGELOG.md
  js/imageeditor/package.json
  js/lite/CHANGELOG.md
  js/lite/package.json
  js/model3D/CHANGELOG.md
  js/model3D/package.json
  js/multimodaltextbox/CHANGELOG.md
  js/multimodaltextbox/package.json
  js/simpleimage/CHANGELOG.md
  js/simpleimage/package.json
  js/upload/CHANGELOG.md
  js/upload/package.json
  js/uploadbutton/CHANGELOG.md
  js/uploadbutton/package.json
  js/video/CHANGELOG.md
  js/video/package.json
Labels: no-visual-update, windows-tests, flaky-tests
