Repository gradio-app/gradio, pull requests merged in 2025-07, with the labels that each got.

#11520 Upgrade mcp version for security
  .changeset/real-eggs-kick.md
  requirements-mcp.txt
Labels: v: patch, t: fix

#11542 set python version
  .changeset/early-bags-throw.md
  .github/workflows/publish.yml
  gradio/components/textbox.py
Labels: v: patch

#11544 testing
  .changeset/plain-pens-wave.md
  gradio/components/textbox.py
Labels: v: patch

#11543 Connection handling messaging
  .changeset/eighty-dots-punch.md
  client/js/src/client.ts
  client/js/src/constants.ts
  client/js/src/helpers/api_info.ts
  client/js/src/types.ts
  client/js/src/utils/stream.ts
  client/js/src/utils/submit.ts
  gradio/routes.py
  gradio/server_messages.py
  js/app/src/routes/[...catchall]/+page.svelte
  js/core/src/Blocks.svelte
  js/spa/src/Index.svelte
  js/statustracker/static/ToastContent.svelte
Labels: v: patch

#11591 fix: add missing space at end of warning sentences for proper grammar
  .changeset/small-ads-hang.md
  gradio/interface.py
Labels: v: patch, t: fix

#11607 Use inspect.getdoc to inherit parent method docstrings in get_function_description
  .changeset/vast-squids-roll.md
  gradio/utils.py
  guides/10_mcp/01_building-mcp-server-with-gradio.md
  test/test_utils.py
Labels: v: patch

#11619 Add a query param for the selected language & make MCP the default option when `mcp_server` is enabled
  .changeset/whole-lands-grin.md
  js/core/src/api_docs/ApiDocs.svelte
Labels: v: patch

#11655 fix flaky tests
  .github/actions/install-all-deps/action.yml
  test/components/test_button.py
Labels: windows-tests, flaky-tests

#11656 fix windows pytests
  test/components/test_button.py
  test/test_docker/test_reverse_proxy/test_reverse_proxy.py
  test/test_docker/test_reverse_proxy_fastapi_mount/test_reverse_proxy_fastapi_mount.py
  test/test_docker/test_reverse_proxy_root_path/test_reverse_proxy_root_path.py
  test/test_helpers.py
  test/test_mcp.py
  test/test_queueing.py
Labels: windows-tests
