Repository gradio-app/gradio, pull requests merged in 2025-08, with the labels that each got.

#11660 CI tweaks
  .github/workflows/generate-changeset.yml
  .github/workflows/npm-previews.yml
  .github/workflows/previews-build.yml
  .github/workflows/publish.yml
  .github/workflows/storybook-build.yml
  .github/workflows/test-functional-lite.yml
  .github/workflows/test-functional.yml
  .github/workflows/test-python.yml
  .github/workflows/tests-js.yml
  .github/workflows/update-checks.yml
  .github/workflows/website-build.yml
  .github/workflows/website-docs-build.yml
  package.json
  pnpm-lock.yaml
Labels: windows-tests

#11666 Fix cached examples bug
  .changeset/hip-eyes-cheat.md
  gradio/components/number.py
  gradio/components/slider.py
  test/test_helpers.py
Labels: v: patch, t: fix

#11686 Some tweaks to Dialogue Component
  .changeset/some-geckos-knock.md
  demo/dialogue_component/run.ipynb
  demo/dialogue_component/run.py
  gradio/components/dialogue.py
  js/dialogue/Dialogue.svelte
  js/dialogue/Index.svelte
  js/dialogue/Switch.svelte
Labels: v: patch

#11692 Fix z-index of icon button wrapper
  .changeset/shaggy-swans-read.md
  js/atoms/src/IconButtonWrapper.svelte
Labels: v: patch, t: fix

#11697 Fix `gr.LoginButton` to work on custom domains
  .changeset/every-feet-shop.md
  gradio/oauth.py
Labels: v: patch, t: fix

#11700 Have `Client` send authorization token with the `X-HF-Authorization` token
  .changeset/solid-bottles-join.md
  client/python/gradio_client/client.py
  gradio/external.py
Labels: v: patch

#11703 Fix flaky tests for release
  .changeset/moody-islands-trade.md
  client/python/test/test_client.py
  gradio/blocks.py
Labels: flaky-tests

#11704 chore: remove no-op setting
  .changeset/salty-heads-knock.md
  js/_website/svelte.config.js
Labels: v: patch

#11744 fix client
  .changeset/khaki-houses-smell.md
  client/python/gradio_client/client.py
Labels: v: patch
