Repository gradio-app/gradio, pull requests merged in 2025-03, with the labels that each got.

#10728 Allow sending a custom TLS certificate or no TLS certificate when connecting to custom share servers
  .changeset/tired-stars-decide.md
  gradio/blocks.py
  gradio/networking.py
  gradio/tunneling.py
  test/test_routes.py
  test/test_tunneling.py
Labels: v: patch

#10694 Event Listeners in gradio sketch
  .changeset/funny-planets-watch.md
  client/js/src/types.ts
  gradio/blocks.py
  gradio/sketch/run.py
  gradio/sketch/sketchbox.py
  home/runner/work/gradio/gradio/client/js/src/types.d.ts
  js/core/src/Blocks.svelte
  js/core/src/types.ts
  js/sidebar/Index.svelte
  js/sketchbox/Index.svelte
Labels: v: patch

#10732 Changed warning stacklevel to improve warnings in console
  .changeset/mighty-rabbits-dance.md
  gradio/components/chatbot.py
Labels: v: patch

#10737 Sidebar fixed positioning
  .changeset/six-lands-sink.md
  guides/03_building-with-blocks/02_controlling-layout.md
  js/sidebar/shared/Sidebar.svelte
Labels: v: patch

#10768 Allow tags for chatbot models using `gr.load`
  .changeset/yummy-shirts-hide.md
  gradio/external.py
Labels: v: patch

#10776 Fix cell selection when using shift + arrow keys
  .changeset/yellow-paws-grin.md
  js/dataframe/shared/selection_utils.ts
Labels: v: patch

#10671 Fixed size for pending thoughts
  .changeset/hot-bees-dream.md
  js/chatbot/shared/Thought.svelte
Labels: v: patch

#10784 On Windows OS, hide `gr.Dataframe` scrollbars while keeping scrolling functionality
  .changeset/better-cooks-jam.md
  demo/matrix_transpose/run.ipynb
  demo/matrix_transpose/run.py
  js/dataframe/shared/VirtualTable.svelte
Labels: v: patch

#10809 Trigger python client release
  .changeset/silly-mammals-train.md
  client/python/CHANGELOG.md
Labels: v: minor, t: feat

#10820 Update `markupsafe` dependency version
  .changeset/sour-buckets-shop.md
  gradio/blocks.py
  gradio/helpers.py
  requirements.txt
Labels: v: patch

#10838 Allow for iterative coding in gradio sketch
  .changeset/famous-books-drop.md
  gradio/sketch/run.py
  gradio/sketch/utils.py
Labels: v: patch

#10870 Change `gr.DeepLinkButton` default variant to be secondary
  .changeset/warm-dragons-admire.md
  gradio/components/deep_link_button.py
Labels: v: patch

#10854 Add support for `mermaid.js` in `Markdown` component (as well as components like `gr.Chatbot` that use Markdown)
  .changeset/legal-crabs-remain.md
  demo/markdown_with_mermaid/run.ipynb
  demo/markdown_with_mermaid/run.py
  js/chatbot/shared/MessageContent.svelte
  js/markdown-code/MarkdownCode.svelte
  js/markdown-code/package.json
  js/markdown-code/utils.ts
  js/markdown/Index.svelte
  js/markdown/Markdown.stories.svelte
  js/markdown/shared/Markdown.svelte
  pnpm-lock.yaml
Labels: v: patch

#10877 Switch from `root_url` to `request.url` in `get_api_call_path()`
  .changeset/public-zoos-obey.md
  gradio/route_utils.py
Labels: v: patch

#10879 Fix request url
  .changeset/some-masks-stay.md
  gradio/route_utils.py
  test/test_routes.py
Labels: v: patch

#10892 Fix minor heartbeat memory leak
  .changeset/clear-vans-push.md
  gradio/routes.py
Labels: v: patch, t: fix

#10891 Fix empty array check in arrow key handling in `gr.Dropdown`
  .changeset/crazy-melons-exist.md
  .changeset/witty-cars-talk.md
  js/dropdown/shared/utils.ts
Labels: v: patch
