Repository gradio-app/gradio, pull requests merged in 2025-02, with the labels that each got.

#10483 Sidebar Fixes
  .changeset/wild-candles-fry.md
  js/sidebar/Index.svelte
  js/sidebar/shared/Sidebar.svelte
Labels: v: patch

#10505 Workaround for Lite to work with multipage client API
  .changeset/green-heads-tan.md
  js/lite/src/LiteIndex.svelte
Labels: v: patch

#10534 Footer alignment fix
  .changeset/modern-flies-jog.md
  js/core/src/Blocks.svelte
Labels: v: patch, t: fix

#10466 Fix the wrapper function of micropip.install to throw the original error for better debug experience
  .changeset/curly-rules-change.md
  js/lite/src/dev/App.svelte
  js/wasm/src/webworker/index.ts
Labels: v: patch, t: fix

#10507 Chatbot `allow_tags`
  .changeset/salty-taxis-unite.md
  gradio/components/chatbot.py
  js/chatbot/Chatbot.test.ts
  js/chatbot/Index.svelte
  js/chatbot/shared/ChatBot.svelte
  js/chatbot/shared/Message.svelte
  js/chatbot/shared/MessageContent.svelte
  js/markdown-code/MarkdownCode.svelte
  test/components/test_chatbot.py
Labels: v: minor

#10544 Fix gr.Plot change/load events and plotly css loaded
  .changeset/blue-olives-fry.md
  gradio/components/plot.py
  guides/10_other-tutorials/developing-faster-with-reload-mode.md
  js/plot/Plot.component.spec.ts
  js/plot/shared/Plot.svelte
  js/plot/shared/plot_types/PlotlyPlot.svelte
Labels: v: patch, t: fix

#10548 Fix DF Postprocess for tuples
  .changeset/floppy-onions-lick.md
  gradio/components/dataframe.py
  test/components/test_dataframe.py
Labels: v: patch, t: fix

#10547 quick_fix_client
  .changeset/olive-pants-judge.md
  client/js/src/client.ts
Labels: v: patch, t: fix

#10579 Fix Sidebar for mobile
  .changeset/nice-glasses-glow.md
  js/sidebar/shared/Sidebar.svelte
Labels: v: patch

#10608 [ZeroGPU] Handshake-based postMessage part.2 (non-SSR mode)
  .changeset/huge-rats-knock.md
  js/spa/src/Index.svelte
Labels: v: patch, t: fix

#10624 Pass kwargs into `gr.ChatInterface` created by `gr.load()`
  .changeset/fast-mammals-hide.md
  gradio/external.py
Labels: v: patch, t: fix

#10646 Fixes cell-selection logic in `Table.svelte`
  .changeset/quick-tires-burn.md
  .changeset/tangy-yaks-open.md
  js/dataframe/shared/Table.svelte
Labels: v: patch

#10650 Fix deployed Spaces
  .changeset/moody-crabs-film.md
  demo/stt_or_tts/run.ipynb
  demo/stt_or_tts/run.py
  gradio/external.py
Labels: v: patch, t: fix

#10670 Update banner to point to FastRTC
  .changeset/wicked-toys-stand.md
  js/_website/src/lib/components/Header.svelte
Labels: v: patch

#10678 Fix Dataframe header type to allow integer values
  .changeset/some-baths-build.md
  demo/blocks_flashcards/run.ipynb
  demo/blocks_flashcards/run.py
  gradio/components/dataframe.py
  js/spa/test/audio_component_events.spec.ts
  js/spa/test/blocks_flashcards.spec.ts
  js/spa/test/dataframe_streaming.spec.ts
  js/spa/test/image_component_events.spec.ts
  js/spa/test/model3d_component_events.spec.ts
  js/spa/test/upload_file_limit_test.spec.ts
Labels: v: patch

#10688 Change `gr.load` chatinterface behavior to streaming
  .changeset/clear-boxes-dance.md
  gradio/external_utils.py
Labels: v: patch
